// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testAccessControls(t *testing.T) {
	t.Parallel()

	query := AccessControls()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testAccessControlsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccessControl{}
	if err = randomize.Struct(seed, o, accessControlDBTypes, true, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AccessControls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAccessControlsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccessControl{}
	if err = randomize.Struct(seed, o, accessControlDBTypes, true, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := AccessControls().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AccessControls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAccessControlsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccessControl{}
	if err = randomize.Struct(seed, o, accessControlDBTypes, true, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AccessControlSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AccessControls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAccessControlsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccessControl{}
	if err = randomize.Struct(seed, o, accessControlDBTypes, true, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := AccessControlExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if AccessControl exists: %s", err)
	}
	if !e {
		t.Errorf("Expected AccessControlExists to return true, but got false.")
	}
}

func testAccessControlsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccessControl{}
	if err = randomize.Struct(seed, o, accessControlDBTypes, true, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	accessControlFound, err := FindAccessControl(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if accessControlFound == nil {
		t.Error("want a record, got nil")
	}
}

func testAccessControlsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccessControl{}
	if err = randomize.Struct(seed, o, accessControlDBTypes, true, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = AccessControls().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testAccessControlsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccessControl{}
	if err = randomize.Struct(seed, o, accessControlDBTypes, true, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := AccessControls().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testAccessControlsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	accessControlOne := &AccessControl{}
	accessControlTwo := &AccessControl{}
	if err = randomize.Struct(seed, accessControlOne, accessControlDBTypes, false, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}
	if err = randomize.Struct(seed, accessControlTwo, accessControlDBTypes, false, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = accessControlOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = accessControlTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AccessControls().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testAccessControlsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	accessControlOne := &AccessControl{}
	accessControlTwo := &AccessControl{}
	if err = randomize.Struct(seed, accessControlOne, accessControlDBTypes, false, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}
	if err = randomize.Struct(seed, accessControlTwo, accessControlDBTypes, false, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = accessControlOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = accessControlTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AccessControls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func accessControlBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *AccessControl) error {
	*o = AccessControl{}
	return nil
}

func accessControlAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *AccessControl) error {
	*o = AccessControl{}
	return nil
}

func accessControlAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *AccessControl) error {
	*o = AccessControl{}
	return nil
}

func accessControlBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AccessControl) error {
	*o = AccessControl{}
	return nil
}

func accessControlAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AccessControl) error {
	*o = AccessControl{}
	return nil
}

func accessControlBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AccessControl) error {
	*o = AccessControl{}
	return nil
}

func accessControlAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AccessControl) error {
	*o = AccessControl{}
	return nil
}

func accessControlBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AccessControl) error {
	*o = AccessControl{}
	return nil
}

func accessControlAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AccessControl) error {
	*o = AccessControl{}
	return nil
}

func testAccessControlsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &AccessControl{}
	o := &AccessControl{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, accessControlDBTypes, false); err != nil {
		t.Errorf("Unable to randomize AccessControl object: %s", err)
	}

	AddAccessControlHook(boil.BeforeInsertHook, accessControlBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	accessControlBeforeInsertHooks = []AccessControlHook{}

	AddAccessControlHook(boil.AfterInsertHook, accessControlAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	accessControlAfterInsertHooks = []AccessControlHook{}

	AddAccessControlHook(boil.AfterSelectHook, accessControlAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	accessControlAfterSelectHooks = []AccessControlHook{}

	AddAccessControlHook(boil.BeforeUpdateHook, accessControlBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	accessControlBeforeUpdateHooks = []AccessControlHook{}

	AddAccessControlHook(boil.AfterUpdateHook, accessControlAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	accessControlAfterUpdateHooks = []AccessControlHook{}

	AddAccessControlHook(boil.BeforeDeleteHook, accessControlBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	accessControlBeforeDeleteHooks = []AccessControlHook{}

	AddAccessControlHook(boil.AfterDeleteHook, accessControlAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	accessControlAfterDeleteHooks = []AccessControlHook{}

	AddAccessControlHook(boil.BeforeUpsertHook, accessControlBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	accessControlBeforeUpsertHooks = []AccessControlHook{}

	AddAccessControlHook(boil.AfterUpsertHook, accessControlAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	accessControlAfterUpsertHooks = []AccessControlHook{}
}

func testAccessControlsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccessControl{}
	if err = randomize.Struct(seed, o, accessControlDBTypes, true, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AccessControls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAccessControlsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccessControl{}
	if err = randomize.Struct(seed, o, accessControlDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(accessControlColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := AccessControls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAccessControlToOnePermissionUsingPermissionIdPermission(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local AccessControl
	var foreign Permission

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, accessControlDBTypes, false, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, permissionDBTypes, false, permissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Permission struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.PermissionId = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.PermissionIdPermission().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddPermissionHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Permission) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := AccessControlSlice{&local}
	if err = local.L.LoadPermissionIdPermission(ctx, tx, false, (*[]*AccessControl)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.PermissionIdPermission == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.PermissionIdPermission = nil
	if err = local.L.LoadPermissionIdPermission(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.PermissionIdPermission == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testAccessControlToOneUserUsingUserIdUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local AccessControl
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, accessControlDBTypes, false, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserId = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.UserIdUser().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := AccessControlSlice{&local}
	if err = local.L.LoadUserIdUser(ctx, tx, false, (*[]*AccessControl)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.UserIdUser == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.UserIdUser = nil
	if err = local.L.LoadUserIdUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.UserIdUser == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testAccessControlToOneSetOpPermissionUsingPermissionIdPermission(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AccessControl
	var b, c Permission

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, accessControlDBTypes, false, strmangle.SetComplement(accessControlPrimaryKeyColumns, accessControlColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, permissionDBTypes, false, strmangle.SetComplement(permissionPrimaryKeyColumns, permissionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, permissionDBTypes, false, strmangle.SetComplement(permissionPrimaryKeyColumns, permissionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Permission{&b, &c} {
		err = a.SetPermissionIdPermission(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.PermissionIdPermission != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.PermissionIdAccessControls[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.PermissionId != x.ID {
			t.Error("foreign key was wrong value", a.PermissionId)
		}

		zero := reflect.Zero(reflect.TypeOf(a.PermissionId))
		reflect.Indirect(reflect.ValueOf(&a.PermissionId)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.PermissionId != x.ID {
			t.Error("foreign key was wrong value", a.PermissionId, x.ID)
		}
	}
}
func testAccessControlToOneSetOpUserUsingUserIdUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AccessControl
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, accessControlDBTypes, false, strmangle.SetComplement(accessControlPrimaryKeyColumns, accessControlColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUserIdUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.UserIdUser != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserIdAccessControls[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserId != x.ID {
			t.Error("foreign key was wrong value", a.UserId)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserId))
		reflect.Indirect(reflect.ValueOf(&a.UserId)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserId != x.ID {
			t.Error("foreign key was wrong value", a.UserId, x.ID)
		}
	}
}

func testAccessControlsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccessControl{}
	if err = randomize.Struct(seed, o, accessControlDBTypes, true, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAccessControlsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccessControl{}
	if err = randomize.Struct(seed, o, accessControlDBTypes, true, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AccessControlSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAccessControlsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AccessControl{}
	if err = randomize.Struct(seed, o, accessControlDBTypes, true, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AccessControls().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	accessControlDBTypes = map[string]string{`ID`: `character varying`, `UserId`: `character varying`, `PermissionId`: `character varying`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`}
	_                    = bytes.MinRead
)

func testAccessControlsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(accessControlPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(accessControlAllColumns) == len(accessControlPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AccessControl{}
	if err = randomize.Struct(seed, o, accessControlDBTypes, true, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AccessControls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, accessControlDBTypes, true, accessControlPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testAccessControlsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(accessControlAllColumns) == len(accessControlPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AccessControl{}
	if err = randomize.Struct(seed, o, accessControlDBTypes, true, accessControlColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AccessControls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, accessControlDBTypes, true, accessControlPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(accessControlAllColumns, accessControlPrimaryKeyColumns) {
		fields = accessControlAllColumns
	} else {
		fields = strmangle.SetComplement(
			accessControlAllColumns,
			accessControlPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := AccessControlSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testAccessControlsUpsert(t *testing.T) {
	t.Parallel()

	if len(accessControlAllColumns) == len(accessControlPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := AccessControl{}
	if err = randomize.Struct(seed, &o, accessControlDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AccessControl: %s", err)
	}

	count, err := AccessControls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, accessControlDBTypes, false, accessControlPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AccessControl struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AccessControl: %s", err)
	}

	count, err = AccessControls().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
