// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// AccessControl is an object representing the database table.
type AccessControl struct {
	ID           string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserId       string    `boil:"userId" json:"userId" toml:"userId" yaml:"userId"`
	PermissionId string    `boil:"permissionId" json:"permissionId" toml:"permissionId" yaml:"permissionId"`
	CreatedAt    null.Time `boil:"createdAt" json:"createdAt,omitempty" toml:"createdAt" yaml:"createdAt,omitempty"`
	UpdatedAt    null.Time `boil:"updatedAt" json:"updatedAt,omitempty" toml:"updatedAt" yaml:"updatedAt,omitempty"`

	R *accessControlR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L accessControlL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AccessControlColumns = struct {
	ID           string
	UserId       string
	PermissionId string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "id",
	UserId:       "userId",
	PermissionId: "permissionId",
	CreatedAt:    "createdAt",
	UpdatedAt:    "updatedAt",
}

var AccessControlTableColumns = struct {
	ID           string
	UserId       string
	PermissionId string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "access_control.id",
	UserId:       "access_control.userId",
	PermissionId: "access_control.permissionId",
	CreatedAt:    "access_control.createdAt",
	UpdatedAt:    "access_control.updatedAt",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod   { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}

func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}

func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}

func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}

func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}

func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}

func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var AccessControlWhere = struct {
	ID           whereHelperstring
	UserId       whereHelperstring
	PermissionId whereHelperstring
	CreatedAt    whereHelpernull_Time
	UpdatedAt    whereHelpernull_Time
}{
	ID:           whereHelperstring{field: "\"access_control\".\"id\""},
	UserId:       whereHelperstring{field: "\"access_control\".\"userId\""},
	PermissionId: whereHelperstring{field: "\"access_control\".\"permissionId\""},
	CreatedAt:    whereHelpernull_Time{field: "\"access_control\".\"createdAt\""},
	UpdatedAt:    whereHelpernull_Time{field: "\"access_control\".\"updatedAt\""},
}

// AccessControlRels is where relationship names are stored.
var AccessControlRels = struct {
	PermissionIdPermission string
	UserIdUser             string
}{
	PermissionIdPermission: "PermissionIdPermission",
	UserIdUser:             "UserIdUser",
}

// accessControlR is where relationships are stored.
type accessControlR struct {
	PermissionIdPermission *Permission `boil:"PermissionIdPermission" json:"PermissionIdPermission" toml:"PermissionIdPermission" yaml:"PermissionIdPermission"`
	UserIdUser             *User       `boil:"UserIdUser" json:"UserIdUser" toml:"UserIdUser" yaml:"UserIdUser"`
}

// NewStruct creates a new relationship struct
func (*accessControlR) NewStruct() *accessControlR {
	return &accessControlR{}
}

func (r *accessControlR) GetPermissionIdPermission() *Permission {
	if r == nil {
		return nil
	}
	return r.PermissionIdPermission
}

func (r *accessControlR) GetUserIdUser() *User {
	if r == nil {
		return nil
	}
	return r.UserIdUser
}

// accessControlL is where Load methods for each relationship are stored.
type accessControlL struct{}

var (
	accessControlAllColumns            = []string{"id", "userId", "permissionId", "createdAt", "updatedAt"}
	accessControlColumnsWithoutDefault = []string{"id", "userId", "permissionId"}
	accessControlColumnsWithDefault    = []string{"createdAt", "updatedAt"}
	accessControlPrimaryKeyColumns     = []string{"id"}
	accessControlGeneratedColumns      = []string{}
)

type (
	// AccessControlSlice is an alias for a slice of pointers to AccessControl.
	// This should almost always be used instead of []AccessControl.
	AccessControlSlice []*AccessControl
	// AccessControlHook is the signature for custom AccessControl hook methods
	AccessControlHook func(context.Context, boil.ContextExecutor, *AccessControl) error

	accessControlQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	accessControlType                 = reflect.TypeOf(&AccessControl{})
	accessControlMapping              = queries.MakeStructMapping(accessControlType)
	accessControlPrimaryKeyMapping, _ = queries.BindMapping(accessControlType, accessControlMapping, accessControlPrimaryKeyColumns)
	accessControlInsertCacheMut       sync.RWMutex
	accessControlInsertCache          = make(map[string]insertCache)
	accessControlUpdateCacheMut       sync.RWMutex
	accessControlUpdateCache          = make(map[string]updateCache)
	accessControlUpsertCacheMut       sync.RWMutex
	accessControlUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var (
	accessControlAfterSelectMu    sync.Mutex
	accessControlAfterSelectHooks []AccessControlHook
)

var (
	accessControlBeforeInsertMu    sync.Mutex
	accessControlBeforeInsertHooks []AccessControlHook
	accessControlAfterInsertMu     sync.Mutex
	accessControlAfterInsertHooks  []AccessControlHook
)

var (
	accessControlBeforeUpdateMu    sync.Mutex
	accessControlBeforeUpdateHooks []AccessControlHook
	accessControlAfterUpdateMu     sync.Mutex
	accessControlAfterUpdateHooks  []AccessControlHook
)

var (
	accessControlBeforeDeleteMu    sync.Mutex
	accessControlBeforeDeleteHooks []AccessControlHook
	accessControlAfterDeleteMu     sync.Mutex
	accessControlAfterDeleteHooks  []AccessControlHook
)

var (
	accessControlBeforeUpsertMu    sync.Mutex
	accessControlBeforeUpsertHooks []AccessControlHook
	accessControlAfterUpsertMu     sync.Mutex
	accessControlAfterUpsertHooks  []AccessControlHook
)

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AccessControl) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessControlAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AccessControl) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessControlBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AccessControl) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessControlAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AccessControl) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessControlBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AccessControl) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessControlAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AccessControl) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessControlBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AccessControl) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessControlAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AccessControl) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessControlBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AccessControl) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessControlAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAccessControlHook registers your hook function for all future operations.
func AddAccessControlHook(hookPoint boil.HookPoint, accessControlHook AccessControlHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		accessControlAfterSelectMu.Lock()
		accessControlAfterSelectHooks = append(accessControlAfterSelectHooks, accessControlHook)
		accessControlAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		accessControlBeforeInsertMu.Lock()
		accessControlBeforeInsertHooks = append(accessControlBeforeInsertHooks, accessControlHook)
		accessControlBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		accessControlAfterInsertMu.Lock()
		accessControlAfterInsertHooks = append(accessControlAfterInsertHooks, accessControlHook)
		accessControlAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		accessControlBeforeUpdateMu.Lock()
		accessControlBeforeUpdateHooks = append(accessControlBeforeUpdateHooks, accessControlHook)
		accessControlBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		accessControlAfterUpdateMu.Lock()
		accessControlAfterUpdateHooks = append(accessControlAfterUpdateHooks, accessControlHook)
		accessControlAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		accessControlBeforeDeleteMu.Lock()
		accessControlBeforeDeleteHooks = append(accessControlBeforeDeleteHooks, accessControlHook)
		accessControlBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		accessControlAfterDeleteMu.Lock()
		accessControlAfterDeleteHooks = append(accessControlAfterDeleteHooks, accessControlHook)
		accessControlAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		accessControlBeforeUpsertMu.Lock()
		accessControlBeforeUpsertHooks = append(accessControlBeforeUpsertHooks, accessControlHook)
		accessControlBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		accessControlAfterUpsertMu.Lock()
		accessControlAfterUpsertHooks = append(accessControlAfterUpsertHooks, accessControlHook)
		accessControlAfterUpsertMu.Unlock()
	}
}

// One returns a single accessControl record from the query.
func (q accessControlQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AccessControl, error) {
	o := &AccessControl{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for access_control")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AccessControl records from the query.
func (q accessControlQuery) All(ctx context.Context, exec boil.ContextExecutor) (AccessControlSlice, error) {
	var o []*AccessControl

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AccessControl slice")
	}

	if len(accessControlAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AccessControl records in the query.
func (q accessControlQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count access_control rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q accessControlQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if access_control exists")
	}

	return count > 0, nil
}

// PermissionIdPermission pointed to by the foreign key.
func (o *AccessControl) PermissionIdPermission(mods ...qm.QueryMod) permissionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PermissionId),
	}

	queryMods = append(queryMods, mods...)

	return Permissions(queryMods...)
}

// UserIdUser pointed to by the foreign key.
func (o *AccessControl) UserIdUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserId),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadPermissionIdPermission allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (accessControlL) LoadPermissionIdPermission(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAccessControl interface{}, mods queries.Applicator) error {
	var slice []*AccessControl
	var object *AccessControl

	if singular {
		var ok bool
		object, ok = maybeAccessControl.(*AccessControl)
		if !ok {
			object = new(AccessControl)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAccessControl)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAccessControl))
			}
		}
	} else {
		s, ok := maybeAccessControl.(*[]*AccessControl)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAccessControl)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAccessControl))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &accessControlR{}
		}
		args[object.PermissionId] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &accessControlR{}
			}

			args[obj.PermissionId] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`permissions`),
		qm.WhereIn(`permissions.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Permission")
	}

	var resultSlice []*Permission
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Permission")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for permissions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for permissions")
	}

	if len(permissionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.PermissionIdPermission = foreign
		if foreign.R == nil {
			foreign.R = &permissionR{}
		}
		foreign.R.PermissionIdAccessControls = append(foreign.R.PermissionIdAccessControls, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PermissionId == foreign.ID {
				local.R.PermissionIdPermission = foreign
				if foreign.R == nil {
					foreign.R = &permissionR{}
				}
				foreign.R.PermissionIdAccessControls = append(foreign.R.PermissionIdAccessControls, local)
				break
			}
		}
	}

	return nil
}

// LoadUserIdUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (accessControlL) LoadUserIdUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAccessControl interface{}, mods queries.Applicator) error {
	var slice []*AccessControl
	var object *AccessControl

	if singular {
		var ok bool
		object, ok = maybeAccessControl.(*AccessControl)
		if !ok {
			object = new(AccessControl)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAccessControl)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAccessControl))
			}
		}
	} else {
		s, ok := maybeAccessControl.(*[]*AccessControl)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAccessControl)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAccessControl))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &accessControlR{}
		}
		args[object.UserId] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &accessControlR{}
			}

			args[obj.UserId] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.UserIdUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserIdAccessControls = append(foreign.R.UserIdAccessControls, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserId == foreign.ID {
				local.R.UserIdUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserIdAccessControls = append(foreign.R.UserIdAccessControls, local)
				break
			}
		}
	}

	return nil
}

// SetPermissionIdPermission of the accessControl to the related item.
// Sets o.R.PermissionIdPermission to related.
// Adds o to related.R.PermissionIdAccessControls.
func (o *AccessControl) SetPermissionIdPermission(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Permission) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"access_control\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"permissionId"}),
		strmangle.WhereClause("\"", "\"", 2, accessControlPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PermissionId = related.ID
	if o.R == nil {
		o.R = &accessControlR{
			PermissionIdPermission: related,
		}
	} else {
		o.R.PermissionIdPermission = related
	}

	if related.R == nil {
		related.R = &permissionR{
			PermissionIdAccessControls: AccessControlSlice{o},
		}
	} else {
		related.R.PermissionIdAccessControls = append(related.R.PermissionIdAccessControls, o)
	}

	return nil
}

// SetUserIdUser of the accessControl to the related item.
// Sets o.R.UserIdUser to related.
// Adds o to related.R.UserIdAccessControls.
func (o *AccessControl) SetUserIdUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"access_control\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"userId"}),
		strmangle.WhereClause("\"", "\"", 2, accessControlPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserId = related.ID
	if o.R == nil {
		o.R = &accessControlR{
			UserIdUser: related,
		}
	} else {
		o.R.UserIdUser = related
	}

	if related.R == nil {
		related.R = &userR{
			UserIdAccessControls: AccessControlSlice{o},
		}
	} else {
		related.R.UserIdAccessControls = append(related.R.UserIdAccessControls, o)
	}

	return nil
}

// AccessControls retrieves all the records using an executor.
func AccessControls(mods ...qm.QueryMod) accessControlQuery {
	mods = append(mods, qm.From("\"access_control\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"access_control\".*"})
	}

	return accessControlQuery{q}
}

// FindAccessControl retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAccessControl(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*AccessControl, error) {
	accessControlObj := &AccessControl{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"access_control\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, accessControlObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from access_control")
	}

	if err = accessControlObj.doAfterSelectHooks(ctx, exec); err != nil {
		return accessControlObj, err
	}

	return accessControlObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AccessControl) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no access_control provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accessControlColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	accessControlInsertCacheMut.RLock()
	cache, cached := accessControlInsertCache[key]
	accessControlInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			accessControlAllColumns,
			accessControlColumnsWithDefault,
			accessControlColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(accessControlType, accessControlMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(accessControlType, accessControlMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"access_control\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"access_control\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into access_control")
	}

	if !cached {
		accessControlInsertCacheMut.Lock()
		accessControlInsertCache[key] = cache
		accessControlInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AccessControl.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AccessControl) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	accessControlUpdateCacheMut.RLock()
	cache, cached := accessControlUpdateCache[key]
	accessControlUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			accessControlAllColumns,
			accessControlPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update access_control, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"access_control\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, accessControlPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(accessControlType, accessControlMapping, append(wl, accessControlPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update access_control row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for access_control")
	}

	if !cached {
		accessControlUpdateCacheMut.Lock()
		accessControlUpdateCache[key] = cache
		accessControlUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q accessControlQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for access_control")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for access_control")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AccessControlSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accessControlPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"access_control\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, accessControlPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in accessControl slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all accessControl")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AccessControl) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no access_control provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accessControlColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	accessControlUpsertCacheMut.RLock()
	cache, cached := accessControlUpsertCache[key]
	accessControlUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			accessControlAllColumns,
			accessControlColumnsWithDefault,
			accessControlColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			accessControlAllColumns,
			accessControlPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert access_control, could not build update column list")
		}

		ret := strmangle.SetComplement(accessControlAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(accessControlPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert access_control, could not build conflict column list")
			}

			conflict = make([]string, len(accessControlPrimaryKeyColumns))
			copy(conflict, accessControlPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"access_control\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(accessControlType, accessControlMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(accessControlType, accessControlMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert access_control")
	}

	if !cached {
		accessControlUpsertCacheMut.Lock()
		accessControlUpsertCache[key] = cache
		accessControlUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AccessControl record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AccessControl) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AccessControl provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), accessControlPrimaryKeyMapping)
	sql := "DELETE FROM \"access_control\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from access_control")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for access_control")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q accessControlQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no accessControlQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from access_control")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for access_control")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AccessControlSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(accessControlBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accessControlPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"access_control\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accessControlPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from accessControl slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for access_control")
	}

	if len(accessControlAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AccessControl) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAccessControl(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccessControlSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AccessControlSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accessControlPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"access_control\".* FROM \"access_control\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accessControlPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AccessControlSlice")
	}

	*o = slice

	return nil
}

// AccessControlExists checks if the AccessControl row exists.
func AccessControlExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"access_control\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if access_control exists")
	}

	return exists, nil
}

// Exists checks if the AccessControl row exists.
func (o *AccessControl) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AccessControlExists(ctx, exec, o.ID)
}
