// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testAuditLogs(t *testing.T) {
	t.Parallel()

	query := AuditLogs()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testAuditLogsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditLog{}
	if err = randomize.Struct(seed, o, auditLogDBTypes, true, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AuditLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAuditLogsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditLog{}
	if err = randomize.Struct(seed, o, auditLogDBTypes, true, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := AuditLogs().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AuditLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAuditLogsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditLog{}
	if err = randomize.Struct(seed, o, auditLogDBTypes, true, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AuditLogSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AuditLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAuditLogsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditLog{}
	if err = randomize.Struct(seed, o, auditLogDBTypes, true, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := AuditLogExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if AuditLog exists: %s", err)
	}
	if !e {
		t.Errorf("Expected AuditLogExists to return true, but got false.")
	}
}

func testAuditLogsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditLog{}
	if err = randomize.Struct(seed, o, auditLogDBTypes, true, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	auditLogFound, err := FindAuditLog(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if auditLogFound == nil {
		t.Error("want a record, got nil")
	}
}

func testAuditLogsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditLog{}
	if err = randomize.Struct(seed, o, auditLogDBTypes, true, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = AuditLogs().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testAuditLogsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditLog{}
	if err = randomize.Struct(seed, o, auditLogDBTypes, true, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := AuditLogs().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testAuditLogsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	auditLogOne := &AuditLog{}
	auditLogTwo := &AuditLog{}
	if err = randomize.Struct(seed, auditLogOne, auditLogDBTypes, false, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}
	if err = randomize.Struct(seed, auditLogTwo, auditLogDBTypes, false, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = auditLogOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = auditLogTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AuditLogs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testAuditLogsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	auditLogOne := &AuditLog{}
	auditLogTwo := &AuditLog{}
	if err = randomize.Struct(seed, auditLogOne, auditLogDBTypes, false, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}
	if err = randomize.Struct(seed, auditLogTwo, auditLogDBTypes, false, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = auditLogOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = auditLogTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AuditLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func auditLogBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *AuditLog) error {
	*o = AuditLog{}
	return nil
}

func auditLogAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *AuditLog) error {
	*o = AuditLog{}
	return nil
}

func auditLogAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *AuditLog) error {
	*o = AuditLog{}
	return nil
}

func auditLogBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AuditLog) error {
	*o = AuditLog{}
	return nil
}

func auditLogAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AuditLog) error {
	*o = AuditLog{}
	return nil
}

func auditLogBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AuditLog) error {
	*o = AuditLog{}
	return nil
}

func auditLogAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AuditLog) error {
	*o = AuditLog{}
	return nil
}

func auditLogBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AuditLog) error {
	*o = AuditLog{}
	return nil
}

func auditLogAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AuditLog) error {
	*o = AuditLog{}
	return nil
}

func testAuditLogsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &AuditLog{}
	o := &AuditLog{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, auditLogDBTypes, false); err != nil {
		t.Errorf("Unable to randomize AuditLog object: %s", err)
	}

	AddAuditLogHook(boil.BeforeInsertHook, auditLogBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	auditLogBeforeInsertHooks = []AuditLogHook{}

	AddAuditLogHook(boil.AfterInsertHook, auditLogAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	auditLogAfterInsertHooks = []AuditLogHook{}

	AddAuditLogHook(boil.AfterSelectHook, auditLogAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	auditLogAfterSelectHooks = []AuditLogHook{}

	AddAuditLogHook(boil.BeforeUpdateHook, auditLogBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	auditLogBeforeUpdateHooks = []AuditLogHook{}

	AddAuditLogHook(boil.AfterUpdateHook, auditLogAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	auditLogAfterUpdateHooks = []AuditLogHook{}

	AddAuditLogHook(boil.BeforeDeleteHook, auditLogBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	auditLogBeforeDeleteHooks = []AuditLogHook{}

	AddAuditLogHook(boil.AfterDeleteHook, auditLogAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	auditLogAfterDeleteHooks = []AuditLogHook{}

	AddAuditLogHook(boil.BeforeUpsertHook, auditLogBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	auditLogBeforeUpsertHooks = []AuditLogHook{}

	AddAuditLogHook(boil.AfterUpsertHook, auditLogAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	auditLogAfterUpsertHooks = []AuditLogHook{}
}

func testAuditLogsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditLog{}
	if err = randomize.Struct(seed, o, auditLogDBTypes, true, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AuditLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAuditLogsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditLog{}
	if err = randomize.Struct(seed, o, auditLogDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(auditLogColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := AuditLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAuditLogToOneResourceUsingResourceIdResource(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local AuditLog
	var foreign Resource

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, auditLogDBTypes, true, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, resourceDBTypes, false, resourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Resource struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.ResourceId, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.ResourceIdResource().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddResourceHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Resource) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := AuditLogSlice{&local}
	if err = local.L.LoadResourceIdResource(ctx, tx, false, (*[]*AuditLog)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.ResourceIdResource == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.ResourceIdResource = nil
	if err = local.L.LoadResourceIdResource(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.ResourceIdResource == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testAuditLogToOneTenantUsingTenantIdTenant(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local AuditLog
	var foreign Tenant

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, auditLogDBTypes, false, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, tenantDBTypes, false, tenantColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tenant struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.TenantId = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.TenantIdTenant().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddTenantHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Tenant) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := AuditLogSlice{&local}
	if err = local.L.LoadTenantIdTenant(ctx, tx, false, (*[]*AuditLog)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.TenantIdTenant == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.TenantIdTenant = nil
	if err = local.L.LoadTenantIdTenant(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.TenantIdTenant == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testAuditLogToOneUserUsingUserIdUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local AuditLog
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, auditLogDBTypes, true, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.UserId, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.UserIdUser().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := AuditLogSlice{&local}
	if err = local.L.LoadUserIdUser(ctx, tx, false, (*[]*AuditLog)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.UserIdUser == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.UserIdUser = nil
	if err = local.L.LoadUserIdUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.UserIdUser == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testAuditLogToOneSetOpResourceUsingResourceIdResource(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AuditLog
	var b, c Resource

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, auditLogDBTypes, false, strmangle.SetComplement(auditLogPrimaryKeyColumns, auditLogColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, resourceDBTypes, false, strmangle.SetComplement(resourcePrimaryKeyColumns, resourceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, resourceDBTypes, false, strmangle.SetComplement(resourcePrimaryKeyColumns, resourceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Resource{&b, &c} {
		err = a.SetResourceIdResource(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.ResourceIdResource != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.ResourceIdAuditLogs[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.ResourceId, x.ID) {
			t.Error("foreign key was wrong value", a.ResourceId)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ResourceId))
		reflect.Indirect(reflect.ValueOf(&a.ResourceId)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.ResourceId, x.ID) {
			t.Error("foreign key was wrong value", a.ResourceId, x.ID)
		}
	}
}

func testAuditLogToOneRemoveOpResourceUsingResourceIdResource(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AuditLog
	var b Resource

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, auditLogDBTypes, false, strmangle.SetComplement(auditLogPrimaryKeyColumns, auditLogColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, resourceDBTypes, false, strmangle.SetComplement(resourcePrimaryKeyColumns, resourceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetResourceIdResource(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveResourceIdResource(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.ResourceIdResource().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.ResourceIdResource != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.ResourceId) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.ResourceIdAuditLogs) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testAuditLogToOneSetOpTenantUsingTenantIdTenant(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AuditLog
	var b, c Tenant

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, auditLogDBTypes, false, strmangle.SetComplement(auditLogPrimaryKeyColumns, auditLogColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, tenantDBTypes, false, strmangle.SetComplement(tenantPrimaryKeyColumns, tenantColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, tenantDBTypes, false, strmangle.SetComplement(tenantPrimaryKeyColumns, tenantColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Tenant{&b, &c} {
		err = a.SetTenantIdTenant(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.TenantIdTenant != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.TenantIdAuditLogs[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.TenantId != x.ID {
			t.Error("foreign key was wrong value", a.TenantId)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TenantId))
		reflect.Indirect(reflect.ValueOf(&a.TenantId)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.TenantId != x.ID {
			t.Error("foreign key was wrong value", a.TenantId, x.ID)
		}
	}
}
func testAuditLogToOneSetOpUserUsingUserIdUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AuditLog
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, auditLogDBTypes, false, strmangle.SetComplement(auditLogPrimaryKeyColumns, auditLogColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUserIdUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.UserIdUser != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserIdAuditLogs[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.UserId, x.ID) {
			t.Error("foreign key was wrong value", a.UserId)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserId))
		reflect.Indirect(reflect.ValueOf(&a.UserId)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.UserId, x.ID) {
			t.Error("foreign key was wrong value", a.UserId, x.ID)
		}
	}
}

func testAuditLogToOneRemoveOpUserUsingUserIdUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AuditLog
	var b User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, auditLogDBTypes, false, strmangle.SetComplement(auditLogPrimaryKeyColumns, auditLogColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetUserIdUser(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveUserIdUser(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.UserIdUser().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.UserIdUser != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.UserId) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.UserIdAuditLogs) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testAuditLogsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditLog{}
	if err = randomize.Struct(seed, o, auditLogDBTypes, true, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAuditLogsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditLog{}
	if err = randomize.Struct(seed, o, auditLogDBTypes, true, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AuditLogSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAuditLogsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AuditLog{}
	if err = randomize.Struct(seed, o, auditLogDBTypes, true, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AuditLogs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	auditLogDBTypes = map[string]string{`ID`: `character varying`, `UserId`: `character varying`, `Action`: `character varying`, `ResourceId`: `character varying`, `Details`: `text`, `Timestamp`: `timestamp without time zone`, `TenantId`: `character varying`}
	_               = bytes.MinRead
)

func testAuditLogsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(auditLogPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(auditLogAllColumns) == len(auditLogPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AuditLog{}
	if err = randomize.Struct(seed, o, auditLogDBTypes, true, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AuditLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, auditLogDBTypes, true, auditLogPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testAuditLogsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(auditLogAllColumns) == len(auditLogPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AuditLog{}
	if err = randomize.Struct(seed, o, auditLogDBTypes, true, auditLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AuditLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, auditLogDBTypes, true, auditLogPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(auditLogAllColumns, auditLogPrimaryKeyColumns) {
		fields = auditLogAllColumns
	} else {
		fields = strmangle.SetComplement(
			auditLogAllColumns,
			auditLogPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := AuditLogSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testAuditLogsUpsert(t *testing.T) {
	t.Parallel()

	if len(auditLogAllColumns) == len(auditLogPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := AuditLog{}
	if err = randomize.Struct(seed, &o, auditLogDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AuditLog: %s", err)
	}

	count, err := AuditLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, auditLogDBTypes, false, auditLogPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AuditLog struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AuditLog: %s", err)
	}

	count, err = AuditLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
