// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// AuditLog is an object representing the database table.
type AuditLog struct {
	ID         string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserId     null.String `boil:"userId" json:"userId,omitempty" toml:"userId" yaml:"userId,omitempty"`
	Action     null.String `boil:"action" json:"action,omitempty" toml:"action" yaml:"action,omitempty"`
	ResourceId null.String `boil:"resourceId" json:"resourceId,omitempty" toml:"resourceId" yaml:"resourceId,omitempty"`
	Details    null.String `boil:"details" json:"details,omitempty" toml:"details" yaml:"details,omitempty"`
	Timestamp  null.Time   `boil:"timestamp" json:"timestamp,omitempty" toml:"timestamp" yaml:"timestamp,omitempty"`
	TenantId   string      `boil:"tenantId" json:"tenantId" toml:"tenantId" yaml:"tenantId"`

	R *auditLogR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L auditLogL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AuditLogColumns = struct {
	ID         string
	UserId     string
	Action     string
	ResourceId string
	Details    string
	Timestamp  string
	TenantId   string
}{
	ID:         "id",
	UserId:     "userId",
	Action:     "action",
	ResourceId: "resourceId",
	Details:    "details",
	Timestamp:  "timestamp",
	TenantId:   "tenantId",
}

var AuditLogTableColumns = struct {
	ID         string
	UserId     string
	Action     string
	ResourceId string
	Details    string
	Timestamp  string
	TenantId   string
}{
	ID:         "audit_logs.id",
	UserId:     "audit_logs.userId",
	Action:     "audit_logs.action",
	ResourceId: "audit_logs.resourceId",
	Details:    "audit_logs.details",
	Timestamp:  "audit_logs.timestamp",
	TenantId:   "audit_logs.tenantId",
}

// Generated where

var AuditLogWhere = struct {
	ID         whereHelperstring
	UserId     whereHelpernull_String
	Action     whereHelpernull_String
	ResourceId whereHelpernull_String
	Details    whereHelpernull_String
	Timestamp  whereHelpernull_Time
	TenantId   whereHelperstring
}{
	ID:         whereHelperstring{field: "\"audit_logs\".\"id\""},
	UserId:     whereHelpernull_String{field: "\"audit_logs\".\"userId\""},
	Action:     whereHelpernull_String{field: "\"audit_logs\".\"action\""},
	ResourceId: whereHelpernull_String{field: "\"audit_logs\".\"resourceId\""},
	Details:    whereHelpernull_String{field: "\"audit_logs\".\"details\""},
	Timestamp:  whereHelpernull_Time{field: "\"audit_logs\".\"timestamp\""},
	TenantId:   whereHelperstring{field: "\"audit_logs\".\"tenantId\""},
}

// AuditLogRels is where relationship names are stored.
var AuditLogRels = struct {
	ResourceIdResource string
	TenantIdTenant     string
	UserIdUser         string
}{
	ResourceIdResource: "ResourceIdResource",
	TenantIdTenant:     "TenantIdTenant",
	UserIdUser:         "UserIdUser",
}

// auditLogR is where relationships are stored.
type auditLogR struct {
	ResourceIdResource *Resource `boil:"ResourceIdResource" json:"ResourceIdResource" toml:"ResourceIdResource" yaml:"ResourceIdResource"`
	TenantIdTenant     *Tenant   `boil:"TenantIdTenant" json:"TenantIdTenant" toml:"TenantIdTenant" yaml:"TenantIdTenant"`
	UserIdUser         *User     `boil:"UserIdUser" json:"UserIdUser" toml:"UserIdUser" yaml:"UserIdUser"`
}

// NewStruct creates a new relationship struct
func (*auditLogR) NewStruct() *auditLogR {
	return &auditLogR{}
}

func (r *auditLogR) GetResourceIdResource() *Resource {
	if r == nil {
		return nil
	}
	return r.ResourceIdResource
}

func (r *auditLogR) GetTenantIdTenant() *Tenant {
	if r == nil {
		return nil
	}
	return r.TenantIdTenant
}

func (r *auditLogR) GetUserIdUser() *User {
	if r == nil {
		return nil
	}
	return r.UserIdUser
}

// auditLogL is where Load methods for each relationship are stored.
type auditLogL struct{}

var (
	auditLogAllColumns            = []string{"id", "userId", "action", "resourceId", "details", "timestamp", "tenantId"}
	auditLogColumnsWithoutDefault = []string{"id", "tenantId"}
	auditLogColumnsWithDefault    = []string{"userId", "action", "resourceId", "details", "timestamp"}
	auditLogPrimaryKeyColumns     = []string{"id"}
	auditLogGeneratedColumns      = []string{}
)

type (
	// AuditLogSlice is an alias for a slice of pointers to AuditLog.
	// This should almost always be used instead of []AuditLog.
	AuditLogSlice []*AuditLog
	// AuditLogHook is the signature for custom AuditLog hook methods
	AuditLogHook func(context.Context, boil.ContextExecutor, *AuditLog) error

	auditLogQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	auditLogType                 = reflect.TypeOf(&AuditLog{})
	auditLogMapping              = queries.MakeStructMapping(auditLogType)
	auditLogPrimaryKeyMapping, _ = queries.BindMapping(auditLogType, auditLogMapping, auditLogPrimaryKeyColumns)
	auditLogInsertCacheMut       sync.RWMutex
	auditLogInsertCache          = make(map[string]insertCache)
	auditLogUpdateCacheMut       sync.RWMutex
	auditLogUpdateCache          = make(map[string]updateCache)
	auditLogUpsertCacheMut       sync.RWMutex
	auditLogUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var auditLogAfterSelectMu sync.Mutex
var auditLogAfterSelectHooks []AuditLogHook

var auditLogBeforeInsertMu sync.Mutex
var auditLogBeforeInsertHooks []AuditLogHook
var auditLogAfterInsertMu sync.Mutex
var auditLogAfterInsertHooks []AuditLogHook

var auditLogBeforeUpdateMu sync.Mutex
var auditLogBeforeUpdateHooks []AuditLogHook
var auditLogAfterUpdateMu sync.Mutex
var auditLogAfterUpdateHooks []AuditLogHook

var auditLogBeforeDeleteMu sync.Mutex
var auditLogBeforeDeleteHooks []AuditLogHook
var auditLogAfterDeleteMu sync.Mutex
var auditLogAfterDeleteHooks []AuditLogHook

var auditLogBeforeUpsertMu sync.Mutex
var auditLogBeforeUpsertHooks []AuditLogHook
var auditLogAfterUpsertMu sync.Mutex
var auditLogAfterUpsertHooks []AuditLogHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AuditLog) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditLogAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AuditLog) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditLogBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AuditLog) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditLogAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AuditLog) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditLogBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AuditLog) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditLogAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AuditLog) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditLogBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AuditLog) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditLogAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AuditLog) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditLogBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AuditLog) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range auditLogAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAuditLogHook registers your hook function for all future operations.
func AddAuditLogHook(hookPoint boil.HookPoint, auditLogHook AuditLogHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		auditLogAfterSelectMu.Lock()
		auditLogAfterSelectHooks = append(auditLogAfterSelectHooks, auditLogHook)
		auditLogAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		auditLogBeforeInsertMu.Lock()
		auditLogBeforeInsertHooks = append(auditLogBeforeInsertHooks, auditLogHook)
		auditLogBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		auditLogAfterInsertMu.Lock()
		auditLogAfterInsertHooks = append(auditLogAfterInsertHooks, auditLogHook)
		auditLogAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		auditLogBeforeUpdateMu.Lock()
		auditLogBeforeUpdateHooks = append(auditLogBeforeUpdateHooks, auditLogHook)
		auditLogBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		auditLogAfterUpdateMu.Lock()
		auditLogAfterUpdateHooks = append(auditLogAfterUpdateHooks, auditLogHook)
		auditLogAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		auditLogBeforeDeleteMu.Lock()
		auditLogBeforeDeleteHooks = append(auditLogBeforeDeleteHooks, auditLogHook)
		auditLogBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		auditLogAfterDeleteMu.Lock()
		auditLogAfterDeleteHooks = append(auditLogAfterDeleteHooks, auditLogHook)
		auditLogAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		auditLogBeforeUpsertMu.Lock()
		auditLogBeforeUpsertHooks = append(auditLogBeforeUpsertHooks, auditLogHook)
		auditLogBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		auditLogAfterUpsertMu.Lock()
		auditLogAfterUpsertHooks = append(auditLogAfterUpsertHooks, auditLogHook)
		auditLogAfterUpsertMu.Unlock()
	}
}

// One returns a single auditLog record from the query.
func (q auditLogQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AuditLog, error) {
	o := &AuditLog{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for audit_logs")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AuditLog records from the query.
func (q auditLogQuery) All(ctx context.Context, exec boil.ContextExecutor) (AuditLogSlice, error) {
	var o []*AuditLog

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AuditLog slice")
	}

	if len(auditLogAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AuditLog records in the query.
func (q auditLogQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count audit_logs rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q auditLogQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if audit_logs exists")
	}

	return count > 0, nil
}

// ResourceIdResource pointed to by the foreign key.
func (o *AuditLog) ResourceIdResource(mods ...qm.QueryMod) resourceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ResourceId),
	}

	queryMods = append(queryMods, mods...)

	return Resources(queryMods...)
}

// TenantIdTenant pointed to by the foreign key.
func (o *AuditLog) TenantIdTenant(mods ...qm.QueryMod) tenantQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TenantId),
	}

	queryMods = append(queryMods, mods...)

	return Tenants(queryMods...)
}

// UserIdUser pointed to by the foreign key.
func (o *AuditLog) UserIdUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserId),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadResourceIdResource allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (auditLogL) LoadResourceIdResource(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAuditLog interface{}, mods queries.Applicator) error {
	var slice []*AuditLog
	var object *AuditLog

	if singular {
		var ok bool
		object, ok = maybeAuditLog.(*AuditLog)
		if !ok {
			object = new(AuditLog)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAuditLog)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAuditLog))
			}
		}
	} else {
		s, ok := maybeAuditLog.(*[]*AuditLog)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAuditLog)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAuditLog))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &auditLogR{}
		}
		if !queries.IsNil(object.ResourceId) {
			args[object.ResourceId] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &auditLogR{}
			}

			if !queries.IsNil(obj.ResourceId) {
				args[obj.ResourceId] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`resources`),
		qm.WhereIn(`resources.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Resource")
	}

	var resultSlice []*Resource
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Resource")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for resources")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for resources")
	}

	if len(resourceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ResourceIdResource = foreign
		if foreign.R == nil {
			foreign.R = &resourceR{}
		}
		foreign.R.ResourceIdAuditLogs = append(foreign.R.ResourceIdAuditLogs, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ResourceId, foreign.ID) {
				local.R.ResourceIdResource = foreign
				if foreign.R == nil {
					foreign.R = &resourceR{}
				}
				foreign.R.ResourceIdAuditLogs = append(foreign.R.ResourceIdAuditLogs, local)
				break
			}
		}
	}

	return nil
}

// LoadTenantIdTenant allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (auditLogL) LoadTenantIdTenant(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAuditLog interface{}, mods queries.Applicator) error {
	var slice []*AuditLog
	var object *AuditLog

	if singular {
		var ok bool
		object, ok = maybeAuditLog.(*AuditLog)
		if !ok {
			object = new(AuditLog)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAuditLog)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAuditLog))
			}
		}
	} else {
		s, ok := maybeAuditLog.(*[]*AuditLog)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAuditLog)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAuditLog))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &auditLogR{}
		}
		args[object.TenantId] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &auditLogR{}
			}

			args[obj.TenantId] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tenants`),
		qm.WhereIn(`tenants.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Tenant")
	}

	var resultSlice []*Tenant
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Tenant")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tenants")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tenants")
	}

	if len(tenantAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.TenantIdTenant = foreign
		if foreign.R == nil {
			foreign.R = &tenantR{}
		}
		foreign.R.TenantIdAuditLogs = append(foreign.R.TenantIdAuditLogs, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TenantId == foreign.ID {
				local.R.TenantIdTenant = foreign
				if foreign.R == nil {
					foreign.R = &tenantR{}
				}
				foreign.R.TenantIdAuditLogs = append(foreign.R.TenantIdAuditLogs, local)
				break
			}
		}
	}

	return nil
}

// LoadUserIdUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (auditLogL) LoadUserIdUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAuditLog interface{}, mods queries.Applicator) error {
	var slice []*AuditLog
	var object *AuditLog

	if singular {
		var ok bool
		object, ok = maybeAuditLog.(*AuditLog)
		if !ok {
			object = new(AuditLog)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAuditLog)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAuditLog))
			}
		}
	} else {
		s, ok := maybeAuditLog.(*[]*AuditLog)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAuditLog)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAuditLog))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &auditLogR{}
		}
		if !queries.IsNil(object.UserId) {
			args[object.UserId] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &auditLogR{}
			}

			if !queries.IsNil(obj.UserId) {
				args[obj.UserId] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.UserIdUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserIdAuditLogs = append(foreign.R.UserIdAuditLogs, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.UserId, foreign.ID) {
				local.R.UserIdUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserIdAuditLogs = append(foreign.R.UserIdAuditLogs, local)
				break
			}
		}
	}

	return nil
}

// SetResourceIdResource of the auditLog to the related item.
// Sets o.R.ResourceIdResource to related.
// Adds o to related.R.ResourceIdAuditLogs.
func (o *AuditLog) SetResourceIdResource(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Resource) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"audit_logs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"resourceId"}),
		strmangle.WhereClause("\"", "\"", 2, auditLogPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ResourceId, related.ID)
	if o.R == nil {
		o.R = &auditLogR{
			ResourceIdResource: related,
		}
	} else {
		o.R.ResourceIdResource = related
	}

	if related.R == nil {
		related.R = &resourceR{
			ResourceIdAuditLogs: AuditLogSlice{o},
		}
	} else {
		related.R.ResourceIdAuditLogs = append(related.R.ResourceIdAuditLogs, o)
	}

	return nil
}

// RemoveResourceIdResource relationship.
// Sets o.R.ResourceIdResource to nil.
// Removes o from all passed in related items' relationships struct.
func (o *AuditLog) RemoveResourceIdResource(ctx context.Context, exec boil.ContextExecutor, related *Resource) error {
	var err error

	queries.SetScanner(&o.ResourceId, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("resourceId")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.ResourceIdResource = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.ResourceIdAuditLogs {
		if queries.Equal(o.ResourceId, ri.ResourceId) {
			continue
		}

		ln := len(related.R.ResourceIdAuditLogs)
		if ln > 1 && i < ln-1 {
			related.R.ResourceIdAuditLogs[i] = related.R.ResourceIdAuditLogs[ln-1]
		}
		related.R.ResourceIdAuditLogs = related.R.ResourceIdAuditLogs[:ln-1]
		break
	}
	return nil
}

// SetTenantIdTenant of the auditLog to the related item.
// Sets o.R.TenantIdTenant to related.
// Adds o to related.R.TenantIdAuditLogs.
func (o *AuditLog) SetTenantIdTenant(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Tenant) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"audit_logs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"tenantId"}),
		strmangle.WhereClause("\"", "\"", 2, auditLogPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TenantId = related.ID
	if o.R == nil {
		o.R = &auditLogR{
			TenantIdTenant: related,
		}
	} else {
		o.R.TenantIdTenant = related
	}

	if related.R == nil {
		related.R = &tenantR{
			TenantIdAuditLogs: AuditLogSlice{o},
		}
	} else {
		related.R.TenantIdAuditLogs = append(related.R.TenantIdAuditLogs, o)
	}

	return nil
}

// SetUserIdUser of the auditLog to the related item.
// Sets o.R.UserIdUser to related.
// Adds o to related.R.UserIdAuditLogs.
func (o *AuditLog) SetUserIdUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"audit_logs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"userId"}),
		strmangle.WhereClause("\"", "\"", 2, auditLogPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.UserId, related.ID)
	if o.R == nil {
		o.R = &auditLogR{
			UserIdUser: related,
		}
	} else {
		o.R.UserIdUser = related
	}

	if related.R == nil {
		related.R = &userR{
			UserIdAuditLogs: AuditLogSlice{o},
		}
	} else {
		related.R.UserIdAuditLogs = append(related.R.UserIdAuditLogs, o)
	}

	return nil
}

// RemoveUserIdUser relationship.
// Sets o.R.UserIdUser to nil.
// Removes o from all passed in related items' relationships struct.
func (o *AuditLog) RemoveUserIdUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.UserId, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("userId")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.UserIdUser = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.UserIdAuditLogs {
		if queries.Equal(o.UserId, ri.UserId) {
			continue
		}

		ln := len(related.R.UserIdAuditLogs)
		if ln > 1 && i < ln-1 {
			related.R.UserIdAuditLogs[i] = related.R.UserIdAuditLogs[ln-1]
		}
		related.R.UserIdAuditLogs = related.R.UserIdAuditLogs[:ln-1]
		break
	}
	return nil
}

// AuditLogs retrieves all the records using an executor.
func AuditLogs(mods ...qm.QueryMod) auditLogQuery {
	mods = append(mods, qm.From("\"audit_logs\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"audit_logs\".*"})
	}

	return auditLogQuery{q}
}

// FindAuditLog retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAuditLog(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*AuditLog, error) {
	auditLogObj := &AuditLog{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"audit_logs\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, auditLogObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from audit_logs")
	}

	if err = auditLogObj.doAfterSelectHooks(ctx, exec); err != nil {
		return auditLogObj, err
	}

	return auditLogObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AuditLog) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no audit_logs provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(auditLogColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	auditLogInsertCacheMut.RLock()
	cache, cached := auditLogInsertCache[key]
	auditLogInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			auditLogAllColumns,
			auditLogColumnsWithDefault,
			auditLogColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(auditLogType, auditLogMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(auditLogType, auditLogMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"audit_logs\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"audit_logs\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into audit_logs")
	}

	if !cached {
		auditLogInsertCacheMut.Lock()
		auditLogInsertCache[key] = cache
		auditLogInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AuditLog.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AuditLog) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	auditLogUpdateCacheMut.RLock()
	cache, cached := auditLogUpdateCache[key]
	auditLogUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			auditLogAllColumns,
			auditLogPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update audit_logs, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"audit_logs\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, auditLogPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(auditLogType, auditLogMapping, append(wl, auditLogPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update audit_logs row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for audit_logs")
	}

	if !cached {
		auditLogUpdateCacheMut.Lock()
		auditLogUpdateCache[key] = cache
		auditLogUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q auditLogQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for audit_logs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for audit_logs")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AuditLogSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), auditLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"audit_logs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, auditLogPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in auditLog slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all auditLog")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AuditLog) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no audit_logs provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(auditLogColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	auditLogUpsertCacheMut.RLock()
	cache, cached := auditLogUpsertCache[key]
	auditLogUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			auditLogAllColumns,
			auditLogColumnsWithDefault,
			auditLogColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			auditLogAllColumns,
			auditLogPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert audit_logs, could not build update column list")
		}

		ret := strmangle.SetComplement(auditLogAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(auditLogPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert audit_logs, could not build conflict column list")
			}

			conflict = make([]string, len(auditLogPrimaryKeyColumns))
			copy(conflict, auditLogPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"audit_logs\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(auditLogType, auditLogMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(auditLogType, auditLogMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert audit_logs")
	}

	if !cached {
		auditLogUpsertCacheMut.Lock()
		auditLogUpsertCache[key] = cache
		auditLogUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AuditLog record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AuditLog) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AuditLog provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), auditLogPrimaryKeyMapping)
	sql := "DELETE FROM \"audit_logs\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from audit_logs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for audit_logs")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q auditLogQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no auditLogQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from audit_logs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for audit_logs")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AuditLogSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(auditLogBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), auditLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"audit_logs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, auditLogPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from auditLog slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for audit_logs")
	}

	if len(auditLogAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AuditLog) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAuditLog(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AuditLogSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AuditLogSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), auditLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"audit_logs\".* FROM \"audit_logs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, auditLogPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AuditLogSlice")
	}

	*o = slice

	return nil
}

// AuditLogExists checks if the AuditLog row exists.
func AuditLogExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"audit_logs\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if audit_logs exists")
	}

	return exists, nil
}

// Exists checks if the AuditLog row exists.
func (o *AuditLog) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AuditLogExists(ctx, exec, o.ID)
}
