// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AccessControl     string
	Actions           string
	APIKeys           string
	AuditLogs         string
	Environments      string
	GooseDBVersion    string
	MagicLinks        string
	OauthAccounts     string
	Permissions       string
	Projects          string
	ResourceHierarchy string
	Resources         string
	RolePermissions   string
	Roles             string
	Secrets           string
	Sessions          string
	TeamMembers       string
	Teams             string
	Tenants           string
	UserCredentials   string
	UserRoles         string
	Users             string
}{
	AccessControl:     "access_control",
	Actions:           "actions",
	APIKeys:           "api_keys",
	AuditLogs:         "audit_logs",
	Environments:      "environments",
	GooseDBVersion:    "goose_db_version",
	MagicLinks:        "magic_links",
	OauthAccounts:     "oauth_accounts",
	Permissions:       "permissions",
	Projects:          "projects",
	ResourceHierarchy: "resource_hierarchy",
	Resources:         "resources",
	RolePermissions:   "role_permissions",
	Roles:             "roles",
	Secrets:           "secrets",
	Sessions:          "sessions",
	TeamMembers:       "team_members",
	Teams:             "teams",
	Tenants:           "tenants",
	UserCredentials:   "user_credentials",
	UserRoles:         "user_roles",
	Users:             "users",
}
