// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testMagicLinks(t *testing.T) {
	t.Parallel()

	query := MagicLinks()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testMagicLinksDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MagicLink{}
	if err = randomize.Struct(seed, o, magicLinkDBTypes, true, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MagicLinks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMagicLinksQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MagicLink{}
	if err = randomize.Struct(seed, o, magicLinkDBTypes, true, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := MagicLinks().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MagicLinks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMagicLinksSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MagicLink{}
	if err = randomize.Struct(seed, o, magicLinkDBTypes, true, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MagicLinkSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MagicLinks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMagicLinksExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MagicLink{}
	if err = randomize.Struct(seed, o, magicLinkDBTypes, true, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := MagicLinkExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if MagicLink exists: %s", err)
	}
	if !e {
		t.Errorf("Expected MagicLinkExists to return true, but got false.")
	}
}

func testMagicLinksFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MagicLink{}
	if err = randomize.Struct(seed, o, magicLinkDBTypes, true, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	magicLinkFound, err := FindMagicLink(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if magicLinkFound == nil {
		t.Error("want a record, got nil")
	}
}

func testMagicLinksBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MagicLink{}
	if err = randomize.Struct(seed, o, magicLinkDBTypes, true, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = MagicLinks().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testMagicLinksOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MagicLink{}
	if err = randomize.Struct(seed, o, magicLinkDBTypes, true, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := MagicLinks().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testMagicLinksAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	magicLinkOne := &MagicLink{}
	magicLinkTwo := &MagicLink{}
	if err = randomize.Struct(seed, magicLinkOne, magicLinkDBTypes, false, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}
	if err = randomize.Struct(seed, magicLinkTwo, magicLinkDBTypes, false, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = magicLinkOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = magicLinkTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MagicLinks().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testMagicLinksCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	magicLinkOne := &MagicLink{}
	magicLinkTwo := &MagicLink{}
	if err = randomize.Struct(seed, magicLinkOne, magicLinkDBTypes, false, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}
	if err = randomize.Struct(seed, magicLinkTwo, magicLinkDBTypes, false, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = magicLinkOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = magicLinkTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MagicLinks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func magicLinkBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *MagicLink) error {
	*o = MagicLink{}
	return nil
}

func magicLinkAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *MagicLink) error {
	*o = MagicLink{}
	return nil
}

func magicLinkAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *MagicLink) error {
	*o = MagicLink{}
	return nil
}

func magicLinkBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MagicLink) error {
	*o = MagicLink{}
	return nil
}

func magicLinkAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MagicLink) error {
	*o = MagicLink{}
	return nil
}

func magicLinkBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MagicLink) error {
	*o = MagicLink{}
	return nil
}

func magicLinkAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MagicLink) error {
	*o = MagicLink{}
	return nil
}

func magicLinkBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MagicLink) error {
	*o = MagicLink{}
	return nil
}

func magicLinkAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MagicLink) error {
	*o = MagicLink{}
	return nil
}

func testMagicLinksHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &MagicLink{}
	o := &MagicLink{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, magicLinkDBTypes, false); err != nil {
		t.Errorf("Unable to randomize MagicLink object: %s", err)
	}

	AddMagicLinkHook(boil.BeforeInsertHook, magicLinkBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	magicLinkBeforeInsertHooks = []MagicLinkHook{}

	AddMagicLinkHook(boil.AfterInsertHook, magicLinkAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	magicLinkAfterInsertHooks = []MagicLinkHook{}

	AddMagicLinkHook(boil.AfterSelectHook, magicLinkAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	magicLinkAfterSelectHooks = []MagicLinkHook{}

	AddMagicLinkHook(boil.BeforeUpdateHook, magicLinkBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	magicLinkBeforeUpdateHooks = []MagicLinkHook{}

	AddMagicLinkHook(boil.AfterUpdateHook, magicLinkAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	magicLinkAfterUpdateHooks = []MagicLinkHook{}

	AddMagicLinkHook(boil.BeforeDeleteHook, magicLinkBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	magicLinkBeforeDeleteHooks = []MagicLinkHook{}

	AddMagicLinkHook(boil.AfterDeleteHook, magicLinkAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	magicLinkAfterDeleteHooks = []MagicLinkHook{}

	AddMagicLinkHook(boil.BeforeUpsertHook, magicLinkBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	magicLinkBeforeUpsertHooks = []MagicLinkHook{}

	AddMagicLinkHook(boil.AfterUpsertHook, magicLinkAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	magicLinkAfterUpsertHooks = []MagicLinkHook{}
}

func testMagicLinksInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MagicLink{}
	if err = randomize.Struct(seed, o, magicLinkDBTypes, true, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MagicLinks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMagicLinksInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MagicLink{}
	if err = randomize.Struct(seed, o, magicLinkDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(magicLinkColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := MagicLinks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMagicLinkToOneUserUsingUserIdUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local MagicLink
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, magicLinkDBTypes, false, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserId = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.UserIdUser().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := MagicLinkSlice{&local}
	if err = local.L.LoadUserIdUser(ctx, tx, false, (*[]*MagicLink)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.UserIdUser == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.UserIdUser = nil
	if err = local.L.LoadUserIdUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.UserIdUser == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testMagicLinkToOneSetOpUserUsingUserIdUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MagicLink
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, magicLinkDBTypes, false, strmangle.SetComplement(magicLinkPrimaryKeyColumns, magicLinkColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUserIdUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.UserIdUser != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserIdMagicLinks[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserId != x.ID {
			t.Error("foreign key was wrong value", a.UserId)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserId))
		reflect.Indirect(reflect.ValueOf(&a.UserId)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserId != x.ID {
			t.Error("foreign key was wrong value", a.UserId, x.ID)
		}
	}
}

func testMagicLinksReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MagicLink{}
	if err = randomize.Struct(seed, o, magicLinkDBTypes, true, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMagicLinksReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MagicLink{}
	if err = randomize.Struct(seed, o, magicLinkDBTypes, true, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MagicLinkSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMagicLinksSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MagicLink{}
	if err = randomize.Struct(seed, o, magicLinkDBTypes, true, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MagicLinks().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	magicLinkDBTypes = map[string]string{`ID`: `character varying`, `UserId`: `character varying`, `Token`: `character varying`, `ExpiresAt`: `timestamp without time zone`, `CreatedAt`: `timestamp without time zone`}
	_                = bytes.MinRead
)

func testMagicLinksUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(magicLinkPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(magicLinkAllColumns) == len(magicLinkPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MagicLink{}
	if err = randomize.Struct(seed, o, magicLinkDBTypes, true, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MagicLinks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, magicLinkDBTypes, true, magicLinkPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testMagicLinksSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(magicLinkAllColumns) == len(magicLinkPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MagicLink{}
	if err = randomize.Struct(seed, o, magicLinkDBTypes, true, magicLinkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MagicLinks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, magicLinkDBTypes, true, magicLinkPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(magicLinkAllColumns, magicLinkPrimaryKeyColumns) {
		fields = magicLinkAllColumns
	} else {
		fields = strmangle.SetComplement(
			magicLinkAllColumns,
			magicLinkPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := MagicLinkSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testMagicLinksUpsert(t *testing.T) {
	t.Parallel()

	if len(magicLinkAllColumns) == len(magicLinkPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := MagicLink{}
	if err = randomize.Struct(seed, &o, magicLinkDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MagicLink: %s", err)
	}

	count, err := MagicLinks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, magicLinkDBTypes, false, magicLinkPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MagicLink struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MagicLink: %s", err)
	}

	count, err = MagicLinks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
