// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Resource is an object representing the database table.
type Resource struct {
	ID        string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name      null.String `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`
	Type      null.String `boil:"type" json:"type,omitempty" toml:"type" yaml:"type,omitempty"`
	TenantId  string      `boil:"tenantId" json:"tenantId" toml:"tenantId" yaml:"tenantId"`
	CreatedAt null.Time   `boil:"createdAt" json:"createdAt,omitempty" toml:"createdAt" yaml:"createdAt,omitempty"`
	UpdatedAt null.Time   `boil:"updatedAt" json:"updatedAt,omitempty" toml:"updatedAt" yaml:"updatedAt,omitempty"`

	R *resourceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L resourceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ResourceColumns = struct {
	ID        string
	Name      string
	Type      string
	TenantId  string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	Name:      "name",
	Type:      "type",
	TenantId:  "tenantId",
	CreatedAt: "createdAt",
	UpdatedAt: "updatedAt",
}

var ResourceTableColumns = struct {
	ID        string
	Name      string
	Type      string
	TenantId  string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "resources.id",
	Name:      "resources.name",
	Type:      "resources.type",
	TenantId:  "resources.tenantId",
	CreatedAt: "resources.createdAt",
	UpdatedAt: "resources.updatedAt",
}

// Generated where

var ResourceWhere = struct {
	ID        whereHelperstring
	Name      whereHelpernull_String
	Type      whereHelpernull_String
	TenantId  whereHelperstring
	CreatedAt whereHelpernull_Time
	UpdatedAt whereHelpernull_Time
}{
	ID:        whereHelperstring{field: "\"resources\".\"id\""},
	Name:      whereHelpernull_String{field: "\"resources\".\"name\""},
	Type:      whereHelpernull_String{field: "\"resources\".\"type\""},
	TenantId:  whereHelperstring{field: "\"resources\".\"tenantId\""},
	CreatedAt: whereHelpernull_Time{field: "\"resources\".\"createdAt\""},
	UpdatedAt: whereHelpernull_Time{field: "\"resources\".\"updatedAt\""},
}

// ResourceRels is where relationship names are stored.
var ResourceRels = struct {
	TenantIdTenant        string
	ResourceIdAuditLogs   string
	ResourceIdPermissions string
	ParentIdResources     string
	ChildIdResources      string
}{
	TenantIdTenant:        "TenantIdTenant",
	ResourceIdAuditLogs:   "ResourceIdAuditLogs",
	ResourceIdPermissions: "ResourceIdPermissions",
	ParentIdResources:     "ParentIdResources",
	ChildIdResources:      "ChildIdResources",
}

// resourceR is where relationships are stored.
type resourceR struct {
	TenantIdTenant        *Tenant         `boil:"TenantIdTenant" json:"TenantIdTenant" toml:"TenantIdTenant" yaml:"TenantIdTenant"`
	ResourceIdAuditLogs   AuditLogSlice   `boil:"ResourceIdAuditLogs" json:"ResourceIdAuditLogs" toml:"ResourceIdAuditLogs" yaml:"ResourceIdAuditLogs"`
	ResourceIdPermissions PermissionSlice `boil:"ResourceIdPermissions" json:"ResourceIdPermissions" toml:"ResourceIdPermissions" yaml:"ResourceIdPermissions"`
	ParentIdResources     ResourceSlice   `boil:"ParentIdResources" json:"ParentIdResources" toml:"ParentIdResources" yaml:"ParentIdResources"`
	ChildIdResources      ResourceSlice   `boil:"ChildIdResources" json:"ChildIdResources" toml:"ChildIdResources" yaml:"ChildIdResources"`
}

// NewStruct creates a new relationship struct
func (*resourceR) NewStruct() *resourceR {
	return &resourceR{}
}

func (r *resourceR) GetTenantIdTenant() *Tenant {
	if r == nil {
		return nil
	}
	return r.TenantIdTenant
}

func (r *resourceR) GetResourceIdAuditLogs() AuditLogSlice {
	if r == nil {
		return nil
	}
	return r.ResourceIdAuditLogs
}

func (r *resourceR) GetResourceIdPermissions() PermissionSlice {
	if r == nil {
		return nil
	}
	return r.ResourceIdPermissions
}

func (r *resourceR) GetParentIdResources() ResourceSlice {
	if r == nil {
		return nil
	}
	return r.ParentIdResources
}

func (r *resourceR) GetChildIdResources() ResourceSlice {
	if r == nil {
		return nil
	}
	return r.ChildIdResources
}

// resourceL is where Load methods for each relationship are stored.
type resourceL struct{}

var (
	resourceAllColumns            = []string{"id", "name", "type", "tenantId", "createdAt", "updatedAt"}
	resourceColumnsWithoutDefault = []string{"id", "tenantId"}
	resourceColumnsWithDefault    = []string{"name", "type", "createdAt", "updatedAt"}
	resourcePrimaryKeyColumns     = []string{"id"}
	resourceGeneratedColumns      = []string{}
)

type (
	// ResourceSlice is an alias for a slice of pointers to Resource.
	// This should almost always be used instead of []Resource.
	ResourceSlice []*Resource
	// ResourceHook is the signature for custom Resource hook methods
	ResourceHook func(context.Context, boil.ContextExecutor, *Resource) error

	resourceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	resourceType                 = reflect.TypeOf(&Resource{})
	resourceMapping              = queries.MakeStructMapping(resourceType)
	resourcePrimaryKeyMapping, _ = queries.BindMapping(resourceType, resourceMapping, resourcePrimaryKeyColumns)
	resourceInsertCacheMut       sync.RWMutex
	resourceInsertCache          = make(map[string]insertCache)
	resourceUpdateCacheMut       sync.RWMutex
	resourceUpdateCache          = make(map[string]updateCache)
	resourceUpsertCacheMut       sync.RWMutex
	resourceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var resourceAfterSelectMu sync.Mutex
var resourceAfterSelectHooks []ResourceHook

var resourceBeforeInsertMu sync.Mutex
var resourceBeforeInsertHooks []ResourceHook
var resourceAfterInsertMu sync.Mutex
var resourceAfterInsertHooks []ResourceHook

var resourceBeforeUpdateMu sync.Mutex
var resourceBeforeUpdateHooks []ResourceHook
var resourceAfterUpdateMu sync.Mutex
var resourceAfterUpdateHooks []ResourceHook

var resourceBeforeDeleteMu sync.Mutex
var resourceBeforeDeleteHooks []ResourceHook
var resourceAfterDeleteMu sync.Mutex
var resourceAfterDeleteHooks []ResourceHook

var resourceBeforeUpsertMu sync.Mutex
var resourceBeforeUpsertHooks []ResourceHook
var resourceAfterUpsertMu sync.Mutex
var resourceAfterUpsertHooks []ResourceHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Resource) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Resource) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Resource) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Resource) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Resource) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Resource) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Resource) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Resource) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Resource) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddResourceHook registers your hook function for all future operations.
func AddResourceHook(hookPoint boil.HookPoint, resourceHook ResourceHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		resourceAfterSelectMu.Lock()
		resourceAfterSelectHooks = append(resourceAfterSelectHooks, resourceHook)
		resourceAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		resourceBeforeInsertMu.Lock()
		resourceBeforeInsertHooks = append(resourceBeforeInsertHooks, resourceHook)
		resourceBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		resourceAfterInsertMu.Lock()
		resourceAfterInsertHooks = append(resourceAfterInsertHooks, resourceHook)
		resourceAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		resourceBeforeUpdateMu.Lock()
		resourceBeforeUpdateHooks = append(resourceBeforeUpdateHooks, resourceHook)
		resourceBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		resourceAfterUpdateMu.Lock()
		resourceAfterUpdateHooks = append(resourceAfterUpdateHooks, resourceHook)
		resourceAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		resourceBeforeDeleteMu.Lock()
		resourceBeforeDeleteHooks = append(resourceBeforeDeleteHooks, resourceHook)
		resourceBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		resourceAfterDeleteMu.Lock()
		resourceAfterDeleteHooks = append(resourceAfterDeleteHooks, resourceHook)
		resourceAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		resourceBeforeUpsertMu.Lock()
		resourceBeforeUpsertHooks = append(resourceBeforeUpsertHooks, resourceHook)
		resourceBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		resourceAfterUpsertMu.Lock()
		resourceAfterUpsertHooks = append(resourceAfterUpsertHooks, resourceHook)
		resourceAfterUpsertMu.Unlock()
	}
}

// One returns a single resource record from the query.
func (q resourceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Resource, error) {
	o := &Resource{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for resources")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Resource records from the query.
func (q resourceQuery) All(ctx context.Context, exec boil.ContextExecutor) (ResourceSlice, error) {
	var o []*Resource

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Resource slice")
	}

	if len(resourceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Resource records in the query.
func (q resourceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count resources rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q resourceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if resources exists")
	}

	return count > 0, nil
}

// TenantIdTenant pointed to by the foreign key.
func (o *Resource) TenantIdTenant(mods ...qm.QueryMod) tenantQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TenantId),
	}

	queryMods = append(queryMods, mods...)

	return Tenants(queryMods...)
}

// ResourceIdAuditLogs retrieves all the audit_log's AuditLogs with an executor via resourceId column.
func (o *Resource) ResourceIdAuditLogs(mods ...qm.QueryMod) auditLogQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"audit_logs\".\"resourceId\"=?", o.ID),
	)

	return AuditLogs(queryMods...)
}

// ResourceIdPermissions retrieves all the permission's Permissions with an executor via resourceId column.
func (o *Resource) ResourceIdPermissions(mods ...qm.QueryMod) permissionQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"permissions\".\"resourceId\"=?", o.ID),
	)

	return Permissions(queryMods...)
}

// ParentIdResources retrieves all the resource's Resources with an executor via id column.
func (o *Resource) ParentIdResources(mods ...qm.QueryMod) resourceQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"resource_hierarchy\" on \"resources\".\"id\" = \"resource_hierarchy\".\"parentId\""),
		qm.Where("\"resource_hierarchy\".\"childId\"=?", o.ID),
	)

	return Resources(queryMods...)
}

// ChildIdResources retrieves all the resource's Resources with an executor via id column.
func (o *Resource) ChildIdResources(mods ...qm.QueryMod) resourceQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"resource_hierarchy\" on \"resources\".\"id\" = \"resource_hierarchy\".\"childId\""),
		qm.Where("\"resource_hierarchy\".\"parentId\"=?", o.ID),
	)

	return Resources(queryMods...)
}

// LoadTenantIdTenant allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (resourceL) LoadTenantIdTenant(ctx context.Context, e boil.ContextExecutor, singular bool, maybeResource interface{}, mods queries.Applicator) error {
	var slice []*Resource
	var object *Resource

	if singular {
		var ok bool
		object, ok = maybeResource.(*Resource)
		if !ok {
			object = new(Resource)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeResource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeResource))
			}
		}
	} else {
		s, ok := maybeResource.(*[]*Resource)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeResource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeResource))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &resourceR{}
		}
		args[object.TenantId] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &resourceR{}
			}

			args[obj.TenantId] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tenants`),
		qm.WhereIn(`tenants.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Tenant")
	}

	var resultSlice []*Tenant
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Tenant")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tenants")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tenants")
	}

	if len(tenantAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.TenantIdTenant = foreign
		if foreign.R == nil {
			foreign.R = &tenantR{}
		}
		foreign.R.TenantIdResources = append(foreign.R.TenantIdResources, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TenantId == foreign.ID {
				local.R.TenantIdTenant = foreign
				if foreign.R == nil {
					foreign.R = &tenantR{}
				}
				foreign.R.TenantIdResources = append(foreign.R.TenantIdResources, local)
				break
			}
		}
	}

	return nil
}

// LoadResourceIdAuditLogs allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (resourceL) LoadResourceIdAuditLogs(ctx context.Context, e boil.ContextExecutor, singular bool, maybeResource interface{}, mods queries.Applicator) error {
	var slice []*Resource
	var object *Resource

	if singular {
		var ok bool
		object, ok = maybeResource.(*Resource)
		if !ok {
			object = new(Resource)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeResource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeResource))
			}
		}
	} else {
		s, ok := maybeResource.(*[]*Resource)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeResource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeResource))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &resourceR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &resourceR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`audit_logs`),
		qm.WhereIn(`audit_logs.resourceId in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load audit_logs")
	}

	var resultSlice []*AuditLog
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice audit_logs")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on audit_logs")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for audit_logs")
	}

	if len(auditLogAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ResourceIdAuditLogs = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &auditLogR{}
			}
			foreign.R.ResourceIdResource = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.ResourceId) {
				local.R.ResourceIdAuditLogs = append(local.R.ResourceIdAuditLogs, foreign)
				if foreign.R == nil {
					foreign.R = &auditLogR{}
				}
				foreign.R.ResourceIdResource = local
				break
			}
		}
	}

	return nil
}

// LoadResourceIdPermissions allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (resourceL) LoadResourceIdPermissions(ctx context.Context, e boil.ContextExecutor, singular bool, maybeResource interface{}, mods queries.Applicator) error {
	var slice []*Resource
	var object *Resource

	if singular {
		var ok bool
		object, ok = maybeResource.(*Resource)
		if !ok {
			object = new(Resource)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeResource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeResource))
			}
		}
	} else {
		s, ok := maybeResource.(*[]*Resource)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeResource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeResource))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &resourceR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &resourceR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`permissions`),
		qm.WhereIn(`permissions.resourceId in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load permissions")
	}

	var resultSlice []*Permission
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice permissions")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on permissions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for permissions")
	}

	if len(permissionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ResourceIdPermissions = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &permissionR{}
			}
			foreign.R.ResourceIdResource = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.ResourceId) {
				local.R.ResourceIdPermissions = append(local.R.ResourceIdPermissions, foreign)
				if foreign.R == nil {
					foreign.R = &permissionR{}
				}
				foreign.R.ResourceIdResource = local
				break
			}
		}
	}

	return nil
}

// LoadParentIdResources allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (resourceL) LoadParentIdResources(ctx context.Context, e boil.ContextExecutor, singular bool, maybeResource interface{}, mods queries.Applicator) error {
	var slice []*Resource
	var object *Resource

	if singular {
		var ok bool
		object, ok = maybeResource.(*Resource)
		if !ok {
			object = new(Resource)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeResource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeResource))
			}
		}
	} else {
		s, ok := maybeResource.(*[]*Resource)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeResource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeResource))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &resourceR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &resourceR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.Select("\"resources\".\"id\", \"resources\".\"name\", \"resources\".\"type\", \"resources\".\"tenantId\", \"resources\".\"createdAt\", \"resources\".\"updatedAt\", \"a\".\"childId\""),
		qm.From("\"resources\""),
		qm.InnerJoin("\"resource_hierarchy\" as \"a\" on \"resources\".\"id\" = \"a\".\"parentId\""),
		qm.WhereIn("\"a\".\"childId\" in ?", argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load resources")
	}

	var resultSlice []*Resource

	var localJoinCols []string
	for results.Next() {
		one := new(Resource)
		var localJoinCol string

		err = results.Scan(&one.ID, &one.Name, &one.Type, &one.TenantId, &one.CreatedAt, &one.UpdatedAt, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for resources")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice resources")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on resources")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for resources")
	}

	if len(resourceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ParentIdResources = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &resourceR{}
			}
			foreign.R.ChildIdResources = append(foreign.R.ChildIdResources, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.ParentIdResources = append(local.R.ParentIdResources, foreign)
				if foreign.R == nil {
					foreign.R = &resourceR{}
				}
				foreign.R.ChildIdResources = append(foreign.R.ChildIdResources, local)
				break
			}
		}
	}

	return nil
}

// LoadChildIdResources allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (resourceL) LoadChildIdResources(ctx context.Context, e boil.ContextExecutor, singular bool, maybeResource interface{}, mods queries.Applicator) error {
	var slice []*Resource
	var object *Resource

	if singular {
		var ok bool
		object, ok = maybeResource.(*Resource)
		if !ok {
			object = new(Resource)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeResource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeResource))
			}
		}
	} else {
		s, ok := maybeResource.(*[]*Resource)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeResource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeResource))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &resourceR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &resourceR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.Select("\"resources\".\"id\", \"resources\".\"name\", \"resources\".\"type\", \"resources\".\"tenantId\", \"resources\".\"createdAt\", \"resources\".\"updatedAt\", \"a\".\"parentId\""),
		qm.From("\"resources\""),
		qm.InnerJoin("\"resource_hierarchy\" as \"a\" on \"resources\".\"id\" = \"a\".\"childId\""),
		qm.WhereIn("\"a\".\"parentId\" in ?", argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load resources")
	}

	var resultSlice []*Resource

	var localJoinCols []string
	for results.Next() {
		one := new(Resource)
		var localJoinCol string

		err = results.Scan(&one.ID, &one.Name, &one.Type, &one.TenantId, &one.CreatedAt, &one.UpdatedAt, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for resources")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice resources")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on resources")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for resources")
	}

	if len(resourceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ChildIdResources = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &resourceR{}
			}
			foreign.R.ParentIdResources = append(foreign.R.ParentIdResources, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.ID == localJoinCol {
				local.R.ChildIdResources = append(local.R.ChildIdResources, foreign)
				if foreign.R == nil {
					foreign.R = &resourceR{}
				}
				foreign.R.ParentIdResources = append(foreign.R.ParentIdResources, local)
				break
			}
		}
	}

	return nil
}

// SetTenantIdTenant of the resource to the related item.
// Sets o.R.TenantIdTenant to related.
// Adds o to related.R.TenantIdResources.
func (o *Resource) SetTenantIdTenant(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Tenant) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"resources\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"tenantId"}),
		strmangle.WhereClause("\"", "\"", 2, resourcePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TenantId = related.ID
	if o.R == nil {
		o.R = &resourceR{
			TenantIdTenant: related,
		}
	} else {
		o.R.TenantIdTenant = related
	}

	if related.R == nil {
		related.R = &tenantR{
			TenantIdResources: ResourceSlice{o},
		}
	} else {
		related.R.TenantIdResources = append(related.R.TenantIdResources, o)
	}

	return nil
}

// AddResourceIdAuditLogs adds the given related objects to the existing relationships
// of the resource, optionally inserting them as new records.
// Appends related to o.R.ResourceIdAuditLogs.
// Sets related.R.ResourceIdResource appropriately.
func (o *Resource) AddResourceIdAuditLogs(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*AuditLog) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.ResourceId, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"audit_logs\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"resourceId"}),
				strmangle.WhereClause("\"", "\"", 2, auditLogPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.ResourceId, o.ID)
		}
	}

	if o.R == nil {
		o.R = &resourceR{
			ResourceIdAuditLogs: related,
		}
	} else {
		o.R.ResourceIdAuditLogs = append(o.R.ResourceIdAuditLogs, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &auditLogR{
				ResourceIdResource: o,
			}
		} else {
			rel.R.ResourceIdResource = o
		}
	}
	return nil
}

// SetResourceIdAuditLogs removes all previously related items of the
// resource replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.ResourceIdResource's ResourceIdAuditLogs accordingly.
// Replaces o.R.ResourceIdAuditLogs with related.
// Sets related.R.ResourceIdResource's ResourceIdAuditLogs accordingly.
func (o *Resource) SetResourceIdAuditLogs(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*AuditLog) error {
	query := "update \"audit_logs\" set \"resourceId\" = null where \"resourceId\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.ResourceIdAuditLogs {
			queries.SetScanner(&rel.ResourceId, nil)
			if rel.R == nil {
				continue
			}

			rel.R.ResourceIdResource = nil
		}
		o.R.ResourceIdAuditLogs = nil
	}

	return o.AddResourceIdAuditLogs(ctx, exec, insert, related...)
}

// RemoveResourceIdAuditLogs relationships from objects passed in.
// Removes related items from R.ResourceIdAuditLogs (uses pointer comparison, removal does not keep order)
// Sets related.R.ResourceIdResource.
func (o *Resource) RemoveResourceIdAuditLogs(ctx context.Context, exec boil.ContextExecutor, related ...*AuditLog) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.ResourceId, nil)
		if rel.R != nil {
			rel.R.ResourceIdResource = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("resourceId")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.ResourceIdAuditLogs {
			if rel != ri {
				continue
			}

			ln := len(o.R.ResourceIdAuditLogs)
			if ln > 1 && i < ln-1 {
				o.R.ResourceIdAuditLogs[i] = o.R.ResourceIdAuditLogs[ln-1]
			}
			o.R.ResourceIdAuditLogs = o.R.ResourceIdAuditLogs[:ln-1]
			break
		}
	}

	return nil
}

// AddResourceIdPermissions adds the given related objects to the existing relationships
// of the resource, optionally inserting them as new records.
// Appends related to o.R.ResourceIdPermissions.
// Sets related.R.ResourceIdResource appropriately.
func (o *Resource) AddResourceIdPermissions(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Permission) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.ResourceId, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"permissions\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"resourceId"}),
				strmangle.WhereClause("\"", "\"", 2, permissionPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.ResourceId, o.ID)
		}
	}

	if o.R == nil {
		o.R = &resourceR{
			ResourceIdPermissions: related,
		}
	} else {
		o.R.ResourceIdPermissions = append(o.R.ResourceIdPermissions, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &permissionR{
				ResourceIdResource: o,
			}
		} else {
			rel.R.ResourceIdResource = o
		}
	}
	return nil
}

// SetResourceIdPermissions removes all previously related items of the
// resource replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.ResourceIdResource's ResourceIdPermissions accordingly.
// Replaces o.R.ResourceIdPermissions with related.
// Sets related.R.ResourceIdResource's ResourceIdPermissions accordingly.
func (o *Resource) SetResourceIdPermissions(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Permission) error {
	query := "update \"permissions\" set \"resourceId\" = null where \"resourceId\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.ResourceIdPermissions {
			queries.SetScanner(&rel.ResourceId, nil)
			if rel.R == nil {
				continue
			}

			rel.R.ResourceIdResource = nil
		}
		o.R.ResourceIdPermissions = nil
	}

	return o.AddResourceIdPermissions(ctx, exec, insert, related...)
}

// RemoveResourceIdPermissions relationships from objects passed in.
// Removes related items from R.ResourceIdPermissions (uses pointer comparison, removal does not keep order)
// Sets related.R.ResourceIdResource.
func (o *Resource) RemoveResourceIdPermissions(ctx context.Context, exec boil.ContextExecutor, related ...*Permission) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.ResourceId, nil)
		if rel.R != nil {
			rel.R.ResourceIdResource = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("resourceId")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.ResourceIdPermissions {
			if rel != ri {
				continue
			}

			ln := len(o.R.ResourceIdPermissions)
			if ln > 1 && i < ln-1 {
				o.R.ResourceIdPermissions[i] = o.R.ResourceIdPermissions[ln-1]
			}
			o.R.ResourceIdPermissions = o.R.ResourceIdPermissions[:ln-1]
			break
		}
	}

	return nil
}

// AddParentIdResources adds the given related objects to the existing relationships
// of the resource, optionally inserting them as new records.
// Appends related to o.R.ParentIdResources.
// Sets related.R.ChildIdResources appropriately.
func (o *Resource) AddParentIdResources(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Resource) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"resource_hierarchy\" (\"childId\", \"parentId\") values ($1, $2)"
		values := []interface{}{o.ID, rel.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &resourceR{
			ParentIdResources: related,
		}
	} else {
		o.R.ParentIdResources = append(o.R.ParentIdResources, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &resourceR{
				ChildIdResources: ResourceSlice{o},
			}
		} else {
			rel.R.ChildIdResources = append(rel.R.ChildIdResources, o)
		}
	}
	return nil
}

// SetParentIdResources removes all previously related items of the
// resource replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.ChildIdResources's ParentIdResources accordingly.
// Replaces o.R.ParentIdResources with related.
// Sets related.R.ChildIdResources's ParentIdResources accordingly.
func (o *Resource) SetParentIdResources(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Resource) error {
	query := "delete from \"resource_hierarchy\" where \"childId\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeParentIdResourcesFromChildIdResourcesSlice(o, related)
	if o.R != nil {
		o.R.ParentIdResources = nil
	}

	return o.AddParentIdResources(ctx, exec, insert, related...)
}

// RemoveParentIdResources relationships from objects passed in.
// Removes related items from R.ParentIdResources (uses pointer comparison, removal does not keep order)
// Sets related.R.ChildIdResources.
func (o *Resource) RemoveParentIdResources(ctx context.Context, exec boil.ContextExecutor, related ...*Resource) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	query := fmt.Sprintf(
		"delete from \"resource_hierarchy\" where \"childId\" = $1 and \"parentId\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []interface{}{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeParentIdResourcesFromChildIdResourcesSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.ParentIdResources {
			if rel != ri {
				continue
			}

			ln := len(o.R.ParentIdResources)
			if ln > 1 && i < ln-1 {
				o.R.ParentIdResources[i] = o.R.ParentIdResources[ln-1]
			}
			o.R.ParentIdResources = o.R.ParentIdResources[:ln-1]
			break
		}
	}

	return nil
}

func removeParentIdResourcesFromChildIdResourcesSlice(o *Resource, related []*Resource) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.ChildIdResources {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.ChildIdResources)
			if ln > 1 && i < ln-1 {
				rel.R.ChildIdResources[i] = rel.R.ChildIdResources[ln-1]
			}
			rel.R.ChildIdResources = rel.R.ChildIdResources[:ln-1]
			break
		}
	}
}

// AddChildIdResources adds the given related objects to the existing relationships
// of the resource, optionally inserting them as new records.
// Appends related to o.R.ChildIdResources.
// Sets related.R.ParentIdResources appropriately.
func (o *Resource) AddChildIdResources(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Resource) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"resource_hierarchy\" (\"parentId\", \"childId\") values ($1, $2)"
		values := []interface{}{o.ID, rel.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &resourceR{
			ChildIdResources: related,
		}
	} else {
		o.R.ChildIdResources = append(o.R.ChildIdResources, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &resourceR{
				ParentIdResources: ResourceSlice{o},
			}
		} else {
			rel.R.ParentIdResources = append(rel.R.ParentIdResources, o)
		}
	}
	return nil
}

// SetChildIdResources removes all previously related items of the
// resource replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.ParentIdResources's ChildIdResources accordingly.
// Replaces o.R.ChildIdResources with related.
// Sets related.R.ParentIdResources's ChildIdResources accordingly.
func (o *Resource) SetChildIdResources(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Resource) error {
	query := "delete from \"resource_hierarchy\" where \"parentId\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeChildIdResourcesFromParentIdResourcesSlice(o, related)
	if o.R != nil {
		o.R.ChildIdResources = nil
	}

	return o.AddChildIdResources(ctx, exec, insert, related...)
}

// RemoveChildIdResources relationships from objects passed in.
// Removes related items from R.ChildIdResources (uses pointer comparison, removal does not keep order)
// Sets related.R.ParentIdResources.
func (o *Resource) RemoveChildIdResources(ctx context.Context, exec boil.ContextExecutor, related ...*Resource) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	query := fmt.Sprintf(
		"delete from \"resource_hierarchy\" where \"parentId\" = $1 and \"childId\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []interface{}{o.ID}
	for _, rel := range related {
		values = append(values, rel.ID)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeChildIdResourcesFromParentIdResourcesSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.ChildIdResources {
			if rel != ri {
				continue
			}

			ln := len(o.R.ChildIdResources)
			if ln > 1 && i < ln-1 {
				o.R.ChildIdResources[i] = o.R.ChildIdResources[ln-1]
			}
			o.R.ChildIdResources = o.R.ChildIdResources[:ln-1]
			break
		}
	}

	return nil
}

func removeChildIdResourcesFromParentIdResourcesSlice(o *Resource, related []*Resource) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.ParentIdResources {
			if o.ID != ri.ID {
				continue
			}

			ln := len(rel.R.ParentIdResources)
			if ln > 1 && i < ln-1 {
				rel.R.ParentIdResources[i] = rel.R.ParentIdResources[ln-1]
			}
			rel.R.ParentIdResources = rel.R.ParentIdResources[:ln-1]
			break
		}
	}
}

// Resources retrieves all the records using an executor.
func Resources(mods ...qm.QueryMod) resourceQuery {
	mods = append(mods, qm.From("\"resources\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"resources\".*"})
	}

	return resourceQuery{q}
}

// FindResource retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindResource(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Resource, error) {
	resourceObj := &Resource{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"resources\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, resourceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from resources")
	}

	if err = resourceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return resourceObj, err
	}

	return resourceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Resource) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no resources provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(resourceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	resourceInsertCacheMut.RLock()
	cache, cached := resourceInsertCache[key]
	resourceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			resourceAllColumns,
			resourceColumnsWithDefault,
			resourceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(resourceType, resourceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(resourceType, resourceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"resources\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"resources\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into resources")
	}

	if !cached {
		resourceInsertCacheMut.Lock()
		resourceInsertCache[key] = cache
		resourceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Resource.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Resource) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	resourceUpdateCacheMut.RLock()
	cache, cached := resourceUpdateCache[key]
	resourceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			resourceAllColumns,
			resourcePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update resources, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"resources\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, resourcePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(resourceType, resourceMapping, append(wl, resourcePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update resources row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for resources")
	}

	if !cached {
		resourceUpdateCacheMut.Lock()
		resourceUpdateCache[key] = cache
		resourceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q resourceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for resources")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for resources")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ResourceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), resourcePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"resources\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, resourcePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in resource slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all resource")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Resource) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no resources provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(resourceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	resourceUpsertCacheMut.RLock()
	cache, cached := resourceUpsertCache[key]
	resourceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			resourceAllColumns,
			resourceColumnsWithDefault,
			resourceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			resourceAllColumns,
			resourcePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert resources, could not build update column list")
		}

		ret := strmangle.SetComplement(resourceAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(resourcePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert resources, could not build conflict column list")
			}

			conflict = make([]string, len(resourcePrimaryKeyColumns))
			copy(conflict, resourcePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"resources\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(resourceType, resourceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(resourceType, resourceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert resources")
	}

	if !cached {
		resourceUpsertCacheMut.Lock()
		resourceUpsertCache[key] = cache
		resourceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Resource record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Resource) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Resource provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), resourcePrimaryKeyMapping)
	sql := "DELETE FROM \"resources\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from resources")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for resources")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q resourceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no resourceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from resources")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for resources")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ResourceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(resourceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), resourcePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"resources\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, resourcePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from resource slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for resources")
	}

	if len(resourceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Resource) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindResource(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ResourceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ResourceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), resourcePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"resources\".* FROM \"resources\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, resourcePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ResourceSlice")
	}

	*o = slice

	return nil
}

// ResourceExists checks if the Resource row exists.
func ResourceExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"resources\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if resources exists")
	}

	return exists, nil
}

// Exists checks if the Resource row exists.
func (o *Resource) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ResourceExists(ctx, exec, o.ID)
}
