// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Secret is an object representing the database table.
type Secret struct {
	ID        string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Key       null.String `boil:"key" json:"key,omitempty" toml:"key" yaml:"key,omitempty"`
	Value     null.String `boil:"value" json:"value,omitempty" toml:"value" yaml:"value,omitempty"`
	TenantId  string      `boil:"tenantId" json:"tenantId" toml:"tenantId" yaml:"tenantId"`
	CreatedAt null.Time   `boil:"createdAt" json:"createdAt,omitempty" toml:"createdAt" yaml:"createdAt,omitempty"`
	UpdatedAt null.Time   `boil:"updatedAt" json:"updatedAt,omitempty" toml:"updatedAt" yaml:"updatedAt,omitempty"`

	R *secretR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L secretL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SecretColumns = struct {
	ID        string
	Key       string
	Value     string
	TenantId  string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	Key:       "key",
	Value:     "value",
	TenantId:  "tenantId",
	CreatedAt: "createdAt",
	UpdatedAt: "updatedAt",
}

var SecretTableColumns = struct {
	ID        string
	Key       string
	Value     string
	TenantId  string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "secrets.id",
	Key:       "secrets.key",
	Value:     "secrets.value",
	TenantId:  "secrets.tenantId",
	CreatedAt: "secrets.createdAt",
	UpdatedAt: "secrets.updatedAt",
}

// Generated where

var SecretWhere = struct {
	ID        whereHelperstring
	Key       whereHelpernull_String
	Value     whereHelpernull_String
	TenantId  whereHelperstring
	CreatedAt whereHelpernull_Time
	UpdatedAt whereHelpernull_Time
}{
	ID:        whereHelperstring{field: "\"secrets\".\"id\""},
	Key:       whereHelpernull_String{field: "\"secrets\".\"key\""},
	Value:     whereHelpernull_String{field: "\"secrets\".\"value\""},
	TenantId:  whereHelperstring{field: "\"secrets\".\"tenantId\""},
	CreatedAt: whereHelpernull_Time{field: "\"secrets\".\"createdAt\""},
	UpdatedAt: whereHelpernull_Time{field: "\"secrets\".\"updatedAt\""},
}

// SecretRels is where relationship names are stored.
var SecretRels = struct {
	TenantIdTenant string
}{
	TenantIdTenant: "TenantIdTenant",
}

// secretR is where relationships are stored.
type secretR struct {
	TenantIdTenant *Tenant `boil:"TenantIdTenant" json:"TenantIdTenant" toml:"TenantIdTenant" yaml:"TenantIdTenant"`
}

// NewStruct creates a new relationship struct
func (*secretR) NewStruct() *secretR {
	return &secretR{}
}

func (r *secretR) GetTenantIdTenant() *Tenant {
	if r == nil {
		return nil
	}
	return r.TenantIdTenant
}

// secretL is where Load methods for each relationship are stored.
type secretL struct{}

var (
	secretAllColumns            = []string{"id", "key", "value", "tenantId", "createdAt", "updatedAt"}
	secretColumnsWithoutDefault = []string{"id", "tenantId"}
	secretColumnsWithDefault    = []string{"key", "value", "createdAt", "updatedAt"}
	secretPrimaryKeyColumns     = []string{"id"}
	secretGeneratedColumns      = []string{}
)

type (
	// SecretSlice is an alias for a slice of pointers to Secret.
	// This should almost always be used instead of []Secret.
	SecretSlice []*Secret
	// SecretHook is the signature for custom Secret hook methods
	SecretHook func(context.Context, boil.ContextExecutor, *Secret) error

	secretQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	secretType                 = reflect.TypeOf(&Secret{})
	secretMapping              = queries.MakeStructMapping(secretType)
	secretPrimaryKeyMapping, _ = queries.BindMapping(secretType, secretMapping, secretPrimaryKeyColumns)
	secretInsertCacheMut       sync.RWMutex
	secretInsertCache          = make(map[string]insertCache)
	secretUpdateCacheMut       sync.RWMutex
	secretUpdateCache          = make(map[string]updateCache)
	secretUpsertCacheMut       sync.RWMutex
	secretUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var secretAfterSelectMu sync.Mutex
var secretAfterSelectHooks []SecretHook

var secretBeforeInsertMu sync.Mutex
var secretBeforeInsertHooks []SecretHook
var secretAfterInsertMu sync.Mutex
var secretAfterInsertHooks []SecretHook

var secretBeforeUpdateMu sync.Mutex
var secretBeforeUpdateHooks []SecretHook
var secretAfterUpdateMu sync.Mutex
var secretAfterUpdateHooks []SecretHook

var secretBeforeDeleteMu sync.Mutex
var secretBeforeDeleteHooks []SecretHook
var secretAfterDeleteMu sync.Mutex
var secretAfterDeleteHooks []SecretHook

var secretBeforeUpsertMu sync.Mutex
var secretBeforeUpsertHooks []SecretHook
var secretAfterUpsertMu sync.Mutex
var secretAfterUpsertHooks []SecretHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Secret) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range secretAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Secret) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range secretBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Secret) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range secretAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Secret) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range secretBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Secret) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range secretAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Secret) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range secretBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Secret) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range secretAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Secret) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range secretBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Secret) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range secretAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSecretHook registers your hook function for all future operations.
func AddSecretHook(hookPoint boil.HookPoint, secretHook SecretHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		secretAfterSelectMu.Lock()
		secretAfterSelectHooks = append(secretAfterSelectHooks, secretHook)
		secretAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		secretBeforeInsertMu.Lock()
		secretBeforeInsertHooks = append(secretBeforeInsertHooks, secretHook)
		secretBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		secretAfterInsertMu.Lock()
		secretAfterInsertHooks = append(secretAfterInsertHooks, secretHook)
		secretAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		secretBeforeUpdateMu.Lock()
		secretBeforeUpdateHooks = append(secretBeforeUpdateHooks, secretHook)
		secretBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		secretAfterUpdateMu.Lock()
		secretAfterUpdateHooks = append(secretAfterUpdateHooks, secretHook)
		secretAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		secretBeforeDeleteMu.Lock()
		secretBeforeDeleteHooks = append(secretBeforeDeleteHooks, secretHook)
		secretBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		secretAfterDeleteMu.Lock()
		secretAfterDeleteHooks = append(secretAfterDeleteHooks, secretHook)
		secretAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		secretBeforeUpsertMu.Lock()
		secretBeforeUpsertHooks = append(secretBeforeUpsertHooks, secretHook)
		secretBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		secretAfterUpsertMu.Lock()
		secretAfterUpsertHooks = append(secretAfterUpsertHooks, secretHook)
		secretAfterUpsertMu.Unlock()
	}
}

// One returns a single secret record from the query.
func (q secretQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Secret, error) {
	o := &Secret{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for secrets")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Secret records from the query.
func (q secretQuery) All(ctx context.Context, exec boil.ContextExecutor) (SecretSlice, error) {
	var o []*Secret

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Secret slice")
	}

	if len(secretAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Secret records in the query.
func (q secretQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count secrets rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q secretQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if secrets exists")
	}

	return count > 0, nil
}

// TenantIdTenant pointed to by the foreign key.
func (o *Secret) TenantIdTenant(mods ...qm.QueryMod) tenantQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TenantId),
	}

	queryMods = append(queryMods, mods...)

	return Tenants(queryMods...)
}

// LoadTenantIdTenant allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (secretL) LoadTenantIdTenant(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSecret interface{}, mods queries.Applicator) error {
	var slice []*Secret
	var object *Secret

	if singular {
		var ok bool
		object, ok = maybeSecret.(*Secret)
		if !ok {
			object = new(Secret)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSecret)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSecret))
			}
		}
	} else {
		s, ok := maybeSecret.(*[]*Secret)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSecret)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSecret))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &secretR{}
		}
		args[object.TenantId] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &secretR{}
			}

			args[obj.TenantId] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tenants`),
		qm.WhereIn(`tenants.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Tenant")
	}

	var resultSlice []*Tenant
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Tenant")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tenants")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tenants")
	}

	if len(tenantAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.TenantIdTenant = foreign
		if foreign.R == nil {
			foreign.R = &tenantR{}
		}
		foreign.R.TenantIdSecrets = append(foreign.R.TenantIdSecrets, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TenantId == foreign.ID {
				local.R.TenantIdTenant = foreign
				if foreign.R == nil {
					foreign.R = &tenantR{}
				}
				foreign.R.TenantIdSecrets = append(foreign.R.TenantIdSecrets, local)
				break
			}
		}
	}

	return nil
}

// SetTenantIdTenant of the secret to the related item.
// Sets o.R.TenantIdTenant to related.
// Adds o to related.R.TenantIdSecrets.
func (o *Secret) SetTenantIdTenant(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Tenant) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"secrets\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"tenantId"}),
		strmangle.WhereClause("\"", "\"", 2, secretPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TenantId = related.ID
	if o.R == nil {
		o.R = &secretR{
			TenantIdTenant: related,
		}
	} else {
		o.R.TenantIdTenant = related
	}

	if related.R == nil {
		related.R = &tenantR{
			TenantIdSecrets: SecretSlice{o},
		}
	} else {
		related.R.TenantIdSecrets = append(related.R.TenantIdSecrets, o)
	}

	return nil
}

// Secrets retrieves all the records using an executor.
func Secrets(mods ...qm.QueryMod) secretQuery {
	mods = append(mods, qm.From("\"secrets\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"secrets\".*"})
	}

	return secretQuery{q}
}

// FindSecret retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSecret(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Secret, error) {
	secretObj := &Secret{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"secrets\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, secretObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from secrets")
	}

	if err = secretObj.doAfterSelectHooks(ctx, exec); err != nil {
		return secretObj, err
	}

	return secretObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Secret) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no secrets provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(secretColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	secretInsertCacheMut.RLock()
	cache, cached := secretInsertCache[key]
	secretInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			secretAllColumns,
			secretColumnsWithDefault,
			secretColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(secretType, secretMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(secretType, secretMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"secrets\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"secrets\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into secrets")
	}

	if !cached {
		secretInsertCacheMut.Lock()
		secretInsertCache[key] = cache
		secretInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Secret.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Secret) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	secretUpdateCacheMut.RLock()
	cache, cached := secretUpdateCache[key]
	secretUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			secretAllColumns,
			secretPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update secrets, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"secrets\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, secretPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(secretType, secretMapping, append(wl, secretPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update secrets row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for secrets")
	}

	if !cached {
		secretUpdateCacheMut.Lock()
		secretUpdateCache[key] = cache
		secretUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q secretQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for secrets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for secrets")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SecretSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), secretPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"secrets\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, secretPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in secret slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all secret")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Secret) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no secrets provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(secretColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	secretUpsertCacheMut.RLock()
	cache, cached := secretUpsertCache[key]
	secretUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			secretAllColumns,
			secretColumnsWithDefault,
			secretColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			secretAllColumns,
			secretPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert secrets, could not build update column list")
		}

		ret := strmangle.SetComplement(secretAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(secretPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert secrets, could not build conflict column list")
			}

			conflict = make([]string, len(secretPrimaryKeyColumns))
			copy(conflict, secretPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"secrets\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(secretType, secretMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(secretType, secretMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert secrets")
	}

	if !cached {
		secretUpsertCacheMut.Lock()
		secretUpsertCache[key] = cache
		secretUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Secret record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Secret) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Secret provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), secretPrimaryKeyMapping)
	sql := "DELETE FROM \"secrets\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from secrets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for secrets")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q secretQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no secretQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from secrets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for secrets")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SecretSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(secretBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), secretPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"secrets\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, secretPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from secret slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for secrets")
	}

	if len(secretAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Secret) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSecret(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SecretSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SecretSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), secretPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"secrets\".* FROM \"secrets\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, secretPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SecretSlice")
	}

	*o = slice

	return nil
}

// SecretExists checks if the Secret row exists.
func SecretExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"secrets\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if secrets exists")
	}

	return exists, nil
}

// Exists checks if the Secret row exists.
func (o *Secret) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SecretExists(ctx, exec, o.ID)
}
