// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSecrets(t *testing.T) {
	t.Parallel()

	query := Secrets()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSecretsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSecretsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Secrets().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSecretsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SecretSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSecretsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SecretExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Secret exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SecretExists to return true, but got false.")
	}
}

func testSecretsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	secretFound, err := FindSecret(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if secretFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSecretsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Secrets().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSecretsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Secrets().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSecretsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	secretOne := &Secret{}
	secretTwo := &Secret{}
	if err = randomize.Struct(seed, secretOne, secretDBTypes, false, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}
	if err = randomize.Struct(seed, secretTwo, secretDBTypes, false, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = secretOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = secretTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Secrets().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSecretsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	secretOne := &Secret{}
	secretTwo := &Secret{}
	if err = randomize.Struct(seed, secretOne, secretDBTypes, false, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}
	if err = randomize.Struct(seed, secretTwo, secretDBTypes, false, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = secretOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = secretTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func secretBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Secret) error {
	*o = Secret{}
	return nil
}

func secretAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Secret) error {
	*o = Secret{}
	return nil
}

func secretAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Secret) error {
	*o = Secret{}
	return nil
}

func secretBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Secret) error {
	*o = Secret{}
	return nil
}

func secretAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Secret) error {
	*o = Secret{}
	return nil
}

func secretBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Secret) error {
	*o = Secret{}
	return nil
}

func secretAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Secret) error {
	*o = Secret{}
	return nil
}

func secretBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Secret) error {
	*o = Secret{}
	return nil
}

func secretAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Secret) error {
	*o = Secret{}
	return nil
}

func testSecretsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Secret{}
	o := &Secret{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, secretDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Secret object: %s", err)
	}

	AddSecretHook(boil.BeforeInsertHook, secretBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	secretBeforeInsertHooks = []SecretHook{}

	AddSecretHook(boil.AfterInsertHook, secretAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	secretAfterInsertHooks = []SecretHook{}

	AddSecretHook(boil.AfterSelectHook, secretAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	secretAfterSelectHooks = []SecretHook{}

	AddSecretHook(boil.BeforeUpdateHook, secretBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	secretBeforeUpdateHooks = []SecretHook{}

	AddSecretHook(boil.AfterUpdateHook, secretAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	secretAfterUpdateHooks = []SecretHook{}

	AddSecretHook(boil.BeforeDeleteHook, secretBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	secretBeforeDeleteHooks = []SecretHook{}

	AddSecretHook(boil.AfterDeleteHook, secretAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	secretAfterDeleteHooks = []SecretHook{}

	AddSecretHook(boil.BeforeUpsertHook, secretBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	secretBeforeUpsertHooks = []SecretHook{}

	AddSecretHook(boil.AfterUpsertHook, secretAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	secretAfterUpsertHooks = []SecretHook{}
}

func testSecretsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSecretsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(secretColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSecretToOneTenantUsingTenantIdTenant(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Secret
	var foreign Tenant

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, secretDBTypes, false, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, tenantDBTypes, false, tenantColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tenant struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.TenantId = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.TenantIdTenant().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddTenantHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Tenant) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := SecretSlice{&local}
	if err = local.L.LoadTenantIdTenant(ctx, tx, false, (*[]*Secret)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.TenantIdTenant == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.TenantIdTenant = nil
	if err = local.L.LoadTenantIdTenant(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.TenantIdTenant == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testSecretToOneSetOpTenantUsingTenantIdTenant(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Secret
	var b, c Tenant

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, secretDBTypes, false, strmangle.SetComplement(secretPrimaryKeyColumns, secretColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, tenantDBTypes, false, strmangle.SetComplement(tenantPrimaryKeyColumns, tenantColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, tenantDBTypes, false, strmangle.SetComplement(tenantPrimaryKeyColumns, tenantColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Tenant{&b, &c} {
		err = a.SetTenantIdTenant(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.TenantIdTenant != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.TenantIdSecrets[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.TenantId != x.ID {
			t.Error("foreign key was wrong value", a.TenantId)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TenantId))
		reflect.Indirect(reflect.ValueOf(&a.TenantId)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.TenantId != x.ID {
			t.Error("foreign key was wrong value", a.TenantId, x.ID)
		}
	}
}

func testSecretsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSecretsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SecretSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSecretsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Secrets().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	secretDBTypes = map[string]string{`ID`: `character varying`, `Key`: `character varying`, `Value`: `character varying`, `TenantId`: `character varying`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`}
	_             = bytes.MinRead
)

func testSecretsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(secretPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(secretAllColumns) == len(secretPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, secretDBTypes, true, secretPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSecretsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(secretAllColumns) == len(secretPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Secret{}
	if err = randomize.Struct(seed, o, secretDBTypes, true, secretColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, secretDBTypes, true, secretPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(secretAllColumns, secretPrimaryKeyColumns) {
		fields = secretAllColumns
	} else {
		fields = strmangle.SetComplement(
			secretAllColumns,
			secretPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SecretSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSecretsUpsert(t *testing.T) {
	t.Parallel()

	if len(secretAllColumns) == len(secretPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Secret{}
	if err = randomize.Struct(seed, &o, secretDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Secret: %s", err)
	}

	count, err := Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, secretDBTypes, false, secretPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Secret struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Secret: %s", err)
	}

	count, err = Secrets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
