// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUserCredentials(t *testing.T) {
	t.Parallel()

	query := UserCredentials()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUserCredentialsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCredential{}
	if err = randomize.Struct(seed, o, userCredentialDBTypes, true, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserCredentials().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserCredentialsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCredential{}
	if err = randomize.Struct(seed, o, userCredentialDBTypes, true, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := UserCredentials().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserCredentials().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserCredentialsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCredential{}
	if err = randomize.Struct(seed, o, userCredentialDBTypes, true, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserCredentialSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserCredentials().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserCredentialsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCredential{}
	if err = randomize.Struct(seed, o, userCredentialDBTypes, true, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UserCredentialExists(ctx, tx, o.UserId)
	if err != nil {
		t.Errorf("Unable to check if UserCredential exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UserCredentialExists to return true, but got false.")
	}
}

func testUserCredentialsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCredential{}
	if err = randomize.Struct(seed, o, userCredentialDBTypes, true, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	userCredentialFound, err := FindUserCredential(ctx, tx, o.UserId)
	if err != nil {
		t.Error(err)
	}

	if userCredentialFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUserCredentialsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCredential{}
	if err = randomize.Struct(seed, o, userCredentialDBTypes, true, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = UserCredentials().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUserCredentialsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCredential{}
	if err = randomize.Struct(seed, o, userCredentialDBTypes, true, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := UserCredentials().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUserCredentialsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	userCredentialOne := &UserCredential{}
	userCredentialTwo := &UserCredential{}
	if err = randomize.Struct(seed, userCredentialOne, userCredentialDBTypes, false, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}
	if err = randomize.Struct(seed, userCredentialTwo, userCredentialDBTypes, false, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userCredentialOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userCredentialTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserCredentials().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUserCredentialsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	userCredentialOne := &UserCredential{}
	userCredentialTwo := &UserCredential{}
	if err = randomize.Struct(seed, userCredentialOne, userCredentialDBTypes, false, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}
	if err = randomize.Struct(seed, userCredentialTwo, userCredentialDBTypes, false, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userCredentialOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userCredentialTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserCredentials().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func userCredentialBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserCredential) error {
	*o = UserCredential{}
	return nil
}

func userCredentialAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserCredential) error {
	*o = UserCredential{}
	return nil
}

func userCredentialAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *UserCredential) error {
	*o = UserCredential{}
	return nil
}

func userCredentialBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserCredential) error {
	*o = UserCredential{}
	return nil
}

func userCredentialAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserCredential) error {
	*o = UserCredential{}
	return nil
}

func userCredentialBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserCredential) error {
	*o = UserCredential{}
	return nil
}

func userCredentialAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserCredential) error {
	*o = UserCredential{}
	return nil
}

func userCredentialBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserCredential) error {
	*o = UserCredential{}
	return nil
}

func userCredentialAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserCredential) error {
	*o = UserCredential{}
	return nil
}

func testUserCredentialsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &UserCredential{}
	o := &UserCredential{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, userCredentialDBTypes, false); err != nil {
		t.Errorf("Unable to randomize UserCredential object: %s", err)
	}

	AddUserCredentialHook(boil.BeforeInsertHook, userCredentialBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	userCredentialBeforeInsertHooks = []UserCredentialHook{}

	AddUserCredentialHook(boil.AfterInsertHook, userCredentialAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	userCredentialAfterInsertHooks = []UserCredentialHook{}

	AddUserCredentialHook(boil.AfterSelectHook, userCredentialAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	userCredentialAfterSelectHooks = []UserCredentialHook{}

	AddUserCredentialHook(boil.BeforeUpdateHook, userCredentialBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	userCredentialBeforeUpdateHooks = []UserCredentialHook{}

	AddUserCredentialHook(boil.AfterUpdateHook, userCredentialAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	userCredentialAfterUpdateHooks = []UserCredentialHook{}

	AddUserCredentialHook(boil.BeforeDeleteHook, userCredentialBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	userCredentialBeforeDeleteHooks = []UserCredentialHook{}

	AddUserCredentialHook(boil.AfterDeleteHook, userCredentialAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	userCredentialAfterDeleteHooks = []UserCredentialHook{}

	AddUserCredentialHook(boil.BeforeUpsertHook, userCredentialBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	userCredentialBeforeUpsertHooks = []UserCredentialHook{}

	AddUserCredentialHook(boil.AfterUpsertHook, userCredentialAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	userCredentialAfterUpsertHooks = []UserCredentialHook{}
}

func testUserCredentialsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCredential{}
	if err = randomize.Struct(seed, o, userCredentialDBTypes, true, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserCredentials().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserCredentialsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCredential{}
	if err = randomize.Struct(seed, o, userCredentialDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(userCredentialColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := UserCredentials().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserCredentialToOneUserUsingUserIdUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local UserCredential
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, userCredentialDBTypes, false, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserId = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.UserIdUser().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := UserCredentialSlice{&local}
	if err = local.L.LoadUserIdUser(ctx, tx, false, (*[]*UserCredential)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.UserIdUser == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.UserIdUser = nil
	if err = local.L.LoadUserIdUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.UserIdUser == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testUserCredentialToOneSetOpUserUsingUserIdUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserCredential
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userCredentialDBTypes, false, strmangle.SetComplement(userCredentialPrimaryKeyColumns, userCredentialColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUserIdUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.UserIdUser != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserIdUserCredential != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserId != x.ID {
			t.Error("foreign key was wrong value", a.UserId)
		}

		if exists, err := UserCredentialExists(ctx, tx, a.UserId); err != nil {
			t.Fatal(err)
		} else if !exists {
			t.Error("want 'a' to exist")
		}

	}
}

func testUserCredentialsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCredential{}
	if err = randomize.Struct(seed, o, userCredentialDBTypes, true, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserCredentialsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCredential{}
	if err = randomize.Struct(seed, o, userCredentialDBTypes, true, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserCredentialSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserCredentialsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserCredential{}
	if err = randomize.Struct(seed, o, userCredentialDBTypes, true, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserCredentials().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	userCredentialDBTypes = map[string]string{`UserId`: `character varying`, `PasswordHash`: `character varying`, `LastLogin`: `timestamp without time zone`}
	_                     = bytes.MinRead
)

func testUserCredentialsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(userCredentialPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(userCredentialAllColumns) == len(userCredentialPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserCredential{}
	if err = randomize.Struct(seed, o, userCredentialDBTypes, true, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserCredentials().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userCredentialDBTypes, true, userCredentialPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUserCredentialsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(userCredentialAllColumns) == len(userCredentialPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserCredential{}
	if err = randomize.Struct(seed, o, userCredentialDBTypes, true, userCredentialColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserCredentials().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userCredentialDBTypes, true, userCredentialPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(userCredentialAllColumns, userCredentialPrimaryKeyColumns) {
		fields = userCredentialAllColumns
	} else {
		fields = strmangle.SetComplement(
			userCredentialAllColumns,
			userCredentialPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UserCredentialSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUserCredentialsUpsert(t *testing.T) {
	t.Parallel()

	if len(userCredentialAllColumns) == len(userCredentialPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := UserCredential{}
	if err = randomize.Struct(seed, &o, userCredentialDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserCredential: %s", err)
	}

	count, err := UserCredentials().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, userCredentialDBTypes, false, userCredentialPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserCredential struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserCredential: %s", err)
	}

	count, err = UserCredentials().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
